var endpoint="https://shub.selectorshub.com/";function showLoginScreen(b){b&&(document.getElementById("register_form").style.display="none",$(".container").show())}
function checkSessionId(){browserType.storage.local.get(["ttlt"],b=>{"undefined"==typeof b.ttlt||"undefined"==b.ttlt||null==b.ttlt||""==b.ttlt?(showLoginScreen(!1),$(".popup__actions__container").removeClass("update-upgrade-panel"),$(".patronRequest .after-login").hide(),$(".upgradeBtn.top.home-login-btn").show(),$(".upgradeBtn.top.after-login-top-upgrade").hide(),window.location.pathname.includes("/side-panel/side-shub-panel.html")&&$("#selectorsHubEleContainer").css("max-height","60px")):(showLoginScreen(!0),
checkUser(b.ttlt),$(".popup__actions__container").addClass("update-upgrade-panel"),$(".patronRequest").children(":not(.after-login)").hide(),$(".patronRequest .after-login").show(),$(".upgradeBtn.top.home-login-btn").hide(),$(".upgradeBtn.top.after-login-top-upgrade").show(),window.location.pathname.includes("/side-panel/side-shub-panel.html")&&$("#selectorsHubEleContainer").css("max-height","calc(100% - 320px)"))})}
$(document).ready(function(){$(".after-login.profile").click(function(){chrome.windows.create({url:chrome.runtime.getURL("devtools-panel/profile.html"),type:"popup",height:500,width:600}).then(function(){}).catch(function(b){})});$("#email-f").on("keyup",function(b){"Enter"!==b.key&&13!==b.keyCode||$(".forgetbtn").click()});$("#password").on("keyup",function(b){"Enter"!==b.key&&13!==b.keyCode||$("#submit_btn").click()});$(".open-forgot-password").click(function(){$(".forgetbtn").show();$("#submit_btn").hide();
$(".password-container").hide();$(".open-forgot-password").hide();$(".open-login").show()});$(".open-login").click(function(){$(".forgetbtn").hide();$("#submit_btn").show();$(".open-forgot-password").show();$(".open-login").hide();$(".password-container").show()});$(".forgetbtn").click(function(){let b=document.getElementById("email").value.trim();loading(!0);$(".forgetbtn").prop("disabled",!0);$(".forgetbtn").val("Please wait");$.ajax({method:"POST",url:endpoint+"user/sendforgot",beforeSend:function(a){a.setRequestHeader("Content-type",
"application/json")},data:JSON.stringify({email:b}),success:function(a,c,d){loading(!1);$(".forgetbtn").prop("disabled",!1);$(".forgetbtn").val("Submit");200==d.status&&a.status?$(".user-status").text(a.message).css("color","green").slideDown():(browserType.storage.local.remove("ttlt"),$(".user-status").text(a.message).css("color","red").slideDown());setTimeout(()=>{$(".user-status").slideUp()},5E3)},error:function(a,c,d){},statusCode:{500:function(a){},401:function(a){}}})});$("#submit_btn").click(function(){let b=
document.getElementById("licence").value.trim();if(""==b)return!1;loading(!0);$("#submit_btn").prop("disabled",!0);$("#submit_btn").val("Please wait");$.ajax({method:"POST",url:endpoint+"user/login",beforeSend:function(a){a.setRequestHeader("Content-type","application/json")},data:JSON.stringify({lk:b}),success:function(a,c,d){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");200==d.status&&a.status?(browserType.storage.local.set({ttlt:a.token}),ttlt=a.token,browserType.storage.local.set({data:a.data,
messages:a.messages},function(){showLoginScreen(!0);browserType.runtime.sendMessage({message:"loggedin"},function(e){})}),loginIssue()):($("#submit_btn").prop("disabled",!1),$("#submit_btn").val("Login"),browserType.storage.local.remove("ttlt"),$(".subscription-status").text(a.message).slideDown(),setTimeout(()=>{$(".subscription-status").slideUp()},5E3),-1<a.message.indexOf("Already")&&$("#three-modal").show())},error:function(a,c,d){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");
$(".invalid-error.invalid-credentails").text("Invalid credentials").slideDown();setTimeout(function(){document.getElementsByClassName("invalid-credentails")[0].style.display="none"},3E3)},statusCode:{500:function(a){},401:function(a){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");$(".invalid-error.invalid-credentails").text("Invalid credentials").slideDown();setTimeout(function(){document.getElementsByClassName("invalid-credentails").style.display="none"},3E3)}}})});
$(document).on("click",".logout-btn",function(){logout()});$(document).on("click",".home-login-btn",function(){document.querySelector(".container").style.display="none";document.querySelector("#register_form").style.display="block";document.querySelector(".top_ads__viewer").style.display="none";setTimeout(()=>{document.querySelector(".top_ads__viewer").style.display="none"},200)});checkSessionId();$(document).on("click",".close-modal",function(){$("#three-modal").hide()});$(document).on("click",".device-close",
function(){let b=parseInt($(this).attr("data-num")),a=document.getElementById("licence").value.trim();if(""==a)return!1;$("#three-modal").hide();loading(!0);$("#submit_btn").prop("disabled",!0);$("#submit_btn").val("Please wait");$.ajax({method:"POST",url:endpoint+"user/remove",beforeSend:function(c){c.setRequestHeader("Content-type","application/json")},data:JSON.stringify({lk:a,num:b}),success:function(c,d,e){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");200==e.status&&
c.status?(browserType.storage.local.set({ttlt:c.token}),ttlt=c.token,browserType.storage.local.set({data:c.data,messages:c.messages},function(){showLoginScreen(!0);browserType.runtime.sendMessage({message:"loggedin"},function(f){})}),loginIssue()):($("#submit_btn").prop("disabled",!1),$("#submit_btn").val("Login"),browserType.storage.local.remove("ttlt"),$(".subscription-status").text(c.message).slideDown(),setTimeout(()=>{$(".subscription-status").slideUp()},5E3),-1<c.message.indexOf("Already")&&
$("#three-modal").show())},error:function(c,d,e){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");$(".invalid-error.invalid-credentails").text("Invalid credentials").slideDown();setTimeout(function(){document.getElementsByClassName("invalid-credentails")[0].style.display="none"},3E3)},statusCode:{500:function(c){},401:function(c){loading(!1);$("#submit_btn").prop("disabled",!1);$("#submit_btn").val("Login");$(".invalid-error.invalid-credentails").text("Invalid credentials").slideDown();
setTimeout(function(){document.getElementsByClassName("invalid-credentails").style.display="none"},3E3)}}})});$(document).on("click","#close_btn",function(){document.querySelector(".container").style.display="block";document.querySelector("#register_form").style.display="none";document.querySelector(".top_ads__viewer").style.display="block"});$(document).on("click","#forgot_pass",function(){$(".email-container, .forgetbtn, #open_login").show();$(".licence-container, #submit_btn, #forgot_pass").hide()});
$(document).on("click","#open_login",function(){$(".email-container, .forgetbtn, #open_login").hide();$(".licence-container, #submit_btn, #forgot_pass").show()})});function loading(b){b?$(".loading-view").show():$(".loading-view").hide()}
function loginIssue(){displayAllAds2([]);$(".ads__text, .ads__container, .ads__viewer, .image__ad, .top_ads__viewer, #image-ads").hide();$(".after-login-footer").show();$(".patronRequest").children(":not(.after-login)").hide();$(".patronRequest .after-login").show();$(".patronRequest").removeClass("hideElement");$(".upgradeBtn.top.home-login-btn").hide();$(".upgradeBtn.top.after-login-top-upgrade").show();browserType.storage.local.remove("fetched_ads");$(".popup__actions__container").addClass("update-upgrade-panel");
browserType.runtime.sendMessage({action:"updateContextMenuAfterLogin"});window.location.pathname.includes("/side-panel/side-shub-panel.html")&&$("#selectorsHubEleContainer").css("max-height","calc(100% - 320px)")}
function logout(){$(".patronRequest").children(":not(.after-login)").show();$(".patronRequest .after-login").hide();browserType.storage.local.get(["ttlt"],b=>{"undefined"!=typeof b.ttlt&&"undefined"!=b.ttlt&&null!=b.ttlt&&""!=b.ttlt&&(logoutUser(b.ttlt),browserType.storage.local.remove("ttlt",function(){$(".upgradeBtn.top.home-login-btn").show();$(".upgradeBtn.top.after-login-top-upgrade").hide();checkSessionId();browserType.runtime.lastError?console.error(`Error removing key 'ttlt': ${browserType.runtime.lastError}`):
console.log("Key 'ttlt' removed successfully.")}))});$(".after-login-footer").hide();$(".ads__text, .ads__container, .ads__viewer, .image__ad, .top_ads__viewer, #image-ads").show();$(".popup__actions__container").removeClass("update-upgrade-panel");fetchingAds();$(".patronRequest").show()}
function logoutUser(b){$(".patronRequest").children(":not(.after-login)").show();$(".patronRequest .after-login").hide();$.ajax({method:"get",url:endpoint+"user/logout",beforeSend:function(a){a.setRequestHeader("Content-type","application/json");a.setRequestHeader("Authorization","Bearer "+b)},success:function(a,c,d){},error:function(a,c,d){},statusCode:{500:function(a){},401:function(a){}}})}
function checkUser(b){$.ajax({method:"get",url:endpoint+"user/get-user",beforeSend:function(a){a.setRequestHeader("Content-type","application/json");a.setRequestHeader("Authorization","Bearer "+b)},success:function(a,c,d){200==d.status&&a.status||logout()},error:function(a,c,d){logout()},statusCode:{500:function(a){logout()},401:function(a){logout()}}})}chrome.runtime.onMessage.addListener(function(b,a,c){console.log("message");b.logout&&logout()});
