/*
 Platform.js
 Copyright 2014-2020 Benjamin Tan
 Copyright 2011-2013 John-David Dalton
 Available under MIT license
*/
var sys=null;
(function(){function Q(b){b=String(b);return b.charAt(0).toUpperCase()+b.slice(1)}function T(b,r){var p=-1,g=b?b.length:0;if("number"==typeof g&&-1<g&&g<=U)for(;++p<g;)r(b[p],p,b);else D(b,r)}function E(b){b=K(b);return/^(?:webOS|i(?:OS|P))/.test(b)?b:Q(b)}function D(b,r){for(var p in b)V.call(b,p)&&r(b[p],p,b)}function y(b){return null==b?Q(b):R.call(b).slice(8,-1)}function W(b,r){var p=null!=b?typeof b[r]:"number";return!/^(?:boolean|number|string|undefined)$/.test(p)&&("object"==p?!!b[r]:!0)}function v(b){return String(b).replace(/([ -])(?!$)/g,
"$1?")}function z(b,r){var p=null;T(b,function(g,f){p=r(p,g,f,b)});return p}function K(b){return String(b).replace(/^ +| +$/g,"")}function F(b){function r(q){return z(q,function(l,k){var t=k.pattern||v(k);!l&&(l=RegExp("\\b"+t+" *\\d+[.\\w_]*","i").exec(b)||RegExp("\\b"+t+" *\\w+-[\\w]*","i").exec(b)||RegExp("\\b"+t+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(b))&&((l=String(k.label&&!RegExp(t,"i").test(k.label)?k.label:l).split("/"))[1]&&!/[\d.]+/.test(l[0])&&(l[0]+=" "+l[1]),k=k.label||
k,l=E(l[0].replace(RegExp(t,"i"),k).replace(RegExp("; *(?:"+k+"[_-])?","i")," ").replace(RegExp("("+k+")[-_.]?(\\w)","i"),"$1 $2")));return l})}function p(q){return z(q,function(l,k){return l||(RegExp(k+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(b)||0)[1]||null})}var g=L,f=b&&"object"==typeof b&&"String"!=y(b);f&&(g=b,b=null);var C=g.navigator||{},e=C.userAgent||"";b||=e;var X=f?!!C.likeChrome:/\bChrome\b/.test(b)&&!/internal|\n/i.test(R.toString()),Y=f?"Object":"ScriptBridgingProxyObject",
M=f?"Object":"Environment",A=f&&g.java?"JavaPackage":y(g.java),Z=f?"Object":"RuntimeObject";M=(A=/\bJava/.test(A)&&g.java)&&y(g.environment)==M;var aa=A?"a":"\u03b1",ba=A?"b":"\u03b2",N=g.document||{},w=g.operamini||g.opera,H=G.test(H=f&&w?w["[[Class]]"]:y(w))?H:w=null,a,I=b;f=[];var J=null,x=b==e;e=x&&w&&"function"==typeof w.version&&w.version();var m=function(q){return z(q,function(l,k){return l||RegExp("\\b"+(k.pattern||v(k))+"\\b","i").exec(b)&&(k.label||k)})}([{label:"EdgeHTML",pattern:"Edge"},
"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),c=function(q){return z(q,function(l,k){return l||RegExp("\\b"+(k.pattern||v(k))+"\\b","i").exec(b)&&(k.label||k)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"(?:Edge|Edg|EdgA|EdgiOS)"},"Midori","Nook Browser","PaleMoon","PhantomJS",
"Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Vivaldi","Waterfox","WebPositive",{label:"Yandex Browser",pattern:"YaBrowser"},{label:"UC Browser",pattern:"UCBrowser"},"Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chromium","Chrome",{label:"Chrome",pattern:"(?:HeadlessChrome)"},
{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),h=r([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",
pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad","iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),n=function(q){return z(q,function(l,k,t){return l||(k[h]||k[/^[a-z]+(?: +[a-z]+\b)*/i.exec(h)]||RegExp("\\b"+v(t)+
"(?:\\b|\\w*\\d)","i").exec(b))&&t})}({Apple:{iPad:1,iPhone:1,iPod:1},Alcatel:{},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},Huawei:{},Lenovo:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Oppo:{},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1},Xiaomi:{Mi:1,Redmi:1}}),
d=function(q){return z(q,function(l,k){var t=k.pattern||v(k);if(!l&&(l=RegExp("\\b"+t+"(?:/[\\d.]+|[ \\w.]*)","i").exec(b))){k=k.label||k;var O={"10.0":"10","6.4":"10 Technical Preview","6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};t&&k&&/^Win/i.test(l)&&!/^Windows Phone /i.test(l)&&(O=O[/[\d.]+$/.exec(l)])&&(l="Windows "+O);l=String(l);t&&k&&(l=l.replace(RegExp(t,"i"),
k));l=E(l.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/," $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return l})}(["Windows Phone","KaiOS","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian",
{label:"DragonFly BSD",pattern:"DragonFly"},"Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac","Windows 98;","Windows "]);m&&=[m];/\bAndroid\b/.test(d)&&!h&&(a=/\bAndroid[^;]*;(.*?)(?:Build|\) AppleWebKit)\b/i.exec(b))&&(h=K(a[1]).replace(/^[a-z]{2}-[a-z]{2};\s*/i,"")||null);n&&!h?h=r([n]):n&&h&&(h=h.replace(RegExp("^("+v(n)+")[-_.\\s]","i"),
n+" ").replace(RegExp("^("+v(n)+")[-_.]?(\\w)","i"),n+" $2"));if(a=/\bGoogle TV\b/.exec(h))h=a[0];/\bSimulator\b/i.test(b)&&(h=(h?h+" ":"")+"Simulator");"Opera Mini"==c&&/\bOPiOS\b/.test(b)&&f.push("running in Turbo/Uncompressed mode");"IE"==c&&/\blike iPhone OS\b/.test(b)?(a=F(b.replace(/like iPhone OS/,"")),n=a.manufacturer,h=a.product):/^iP/.test(h)?(c||="Safari",d="iOS"+((a=/ OS ([\d_]+)/i.exec(b))?" "+a[1].replace(/_/g,"."):"")):"Konqueror"==c&&/^Linux\b/i.test(d)?d="Kubuntu":n&&"Google"!=n&&
(/Chrome/.test(c)&&!/\bMobile Safari\b/i.test(b)||/\bVita\b/.test(h))||/\bAndroid\b/.test(d)&&/^Chrome/.test(c)&&/\bVersion\//i.test(b)?(c="Android Browser",d=/\bAndroid\b/.test(d)?d:"Android"):"Silk"==c?(/\bMobi/i.test(b)||(d="Android",f.unshift("desktop mode")),/Accelerated *= *true/i.test(b)&&f.unshift("accelerated")):"UC Browser"==c&&/\bUCWEB\b/.test(b)?f.push("speed mode"):"PaleMoon"==c&&(a=/\bFirefox\/([\d.]+)\b/.exec(b))?f.push("identifying as Firefox "+a[1]):"Firefox"==c&&(a=/\b(Mobile|Tablet|TV)\b/i.exec(b))?
(d||="Firefox OS",h||=a[1]):!c||(a=!/\bMinefield\b/i.test(b)&&/\b(?:Firefox|Safari)\b/.exec(c))?(c&&!h&&/[\/,]|^[^(]+?\)/.test(b.slice(b.indexOf(a+"/")+8))&&(c=null),(a=h||n||d)&&(h||n||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(d))&&(c=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(d)?d:a)+" Browser")):"Electron"==c&&(a=(/\bChrome\/([\d.]+)\b/.exec(b)||0)[1])&&f.push("Chromium "+a);e||=p(["(?:Cloud9|CriOS|CrMo|Edge|Edg|EdgA|EdgiOS|FxiOS|HeadlessChrome|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$)|UCBrowser|YaBrowser)",
"Version",v(c),"(?:Firefox|Minefield|NetFront)"]);if(a="iCab"==m&&3<parseFloat(e)&&"WebKit"||/\bOpera\b/.test(c)&&(/\bOPR\b/.test(b)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(b)&&!/^(?:Trident|EdgeHTML)$/.test(m)&&"WebKit"||!m&&/\bMSIE\b/i.test(b)&&("Mac OS"==d?"Tasman":"Trident")||"WebKit"==m&&/\bPlayStation\b(?! Vita\b)/i.test(c)&&"NetFront")m=[a];"IE"==c&&(a=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(b)||0)[1])?(c+=" Mobile",d="Windows Phone "+(/\+$/.test(a)?a:a+".x"),f.unshift("desktop mode")):
/\bWPDesktop\b/i.test(b)?(c="IE Mobile",d="Windows Phone 8.x",f.unshift("desktop mode"),e||=(/\brv:([\d.]+)/.exec(b)||0)[1]):"IE"!=c&&"Trident"==m&&(a=/\brv:([\d.]+)/.exec(b))&&(c&&f.push("identifying as "+c+(e?" "+e:"")),c="IE",e=a[1]);if(x){if(W(g,"global"))if(A&&(a=A.lang.System,I=a.getProperty("os.arch"),d=d||a.getProperty("os.name")+" "+a.getProperty("os.version")),M){try{e=g.require("ringo/engine").version.join("."),c="RingoJS"}catch(q){(a=g.system)&&a.global.system==g.system&&(c="Narwhal",
d||=a[0].os||null)}c||="Rhino"}else"object"==typeof g.process&&!g.process.browser&&(a=g.process)&&("object"==typeof a.versions&&("string"==typeof a.versions.electron?(f.push("Node "+a.versions.node),c="Electron",e=a.versions.electron):"string"==typeof a.versions.nw&&(f.push("Chromium "+e,"Node "+a.versions.node),c="NW.js",e=a.versions.nw)),c||(c="Node.js",I=a.arch,d=a.platform,e=(e=/[\d.]+/.exec(a.version))?e[0]:null));else y(a=g.runtime)==Y?(c="Adobe AIR",d=a.flash.system.Capabilities.os):y(a=g.phantom)==
Z?(c="PhantomJS",e=(a=a.version||null)&&a.major+"."+a.minor+"."+a.patch):"number"==typeof N.documentMode&&(a=/\bTrident\/(\d+)/i.exec(b))?(e=[e,N.documentMode],(a=+a[1]+4)!=e[1]&&(f.push("IE "+e[1]+" mode"),m&&(m[1]=""),e[1]=a),e="IE"==c?String(e[1].toFixed(1)):e[0]):"number"==typeof N.documentMode&&/^(?:Chrome|Firefox)\b/.test(c)&&(f.push("masking as "+c+" "+e),c="IE",e="11.0",m=["Trident"],d="Windows");d=d&&E(d)}e&&(a=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(e)||/(?:alpha|beta)(?: ?\d)?/i.exec(b+
";"+(x&&C.appMinorVersion))||/\bMinefield\b/i.test(b)&&"a")&&(J=/b/i.test(a)?"beta":"alpha",e=e.replace(RegExp(a+"\\+?$"),"")+("beta"==J?ba:aa)+(/\d+\+?/.exec(a)||""));if("Fennec"==c||"Firefox"==c&&/\b(?:Android|Firefox OS|KaiOS)\b/.test(d))c="Firefox Mobile";else if("Maxthon"==c&&e)e=e.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(h))"Xbox 360"==h&&(d=null),"Xbox 360"==h&&/\bIEMobile\b/.test(b)&&f.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(c)&&(!c||h||/Browser|Mobi/.test(c))||
"Windows CE"!=d&&!/Mobi/i.test(b))if("IE"==c&&x)try{null===g.external&&f.unshift("platform preview")}catch(q){f.unshift("embedded")}else(/\bBlackBerry\b/.test(h)||/\bBB10\b/.test(b))&&(a=(RegExp(h.replace(/ +/g," *")+"/([.\\d]+)","i").exec(b)||0)[1]||e)?(a=[a,/BB10/.test(b)],d=(a[1]?(h=null,n="BlackBerry"):"Device Software")+" "+a[0],e=null):this!=D&&"Wii"!=h&&(x&&w||/Opera/.test(c)&&/\b(?:MSIE|Firefox)\b/i.test(b)||"Firefox"==c&&/\bOS X (?:\d+\.){2,}/.test(d)||"IE"==c&&(d&&!/^Win/.test(d)&&5.5<e||
/\bWindows XP\b/.test(d)&&8<e||8==e&&!/\bTrident\b/.test(b)))&&!G.test(a=F.call(D,b.replace(G,"")+";"))&&a.name&&(a="ing as "+a.name+((a=a.version)?" "+a:""),G.test(c)?(/\bIE\b/.test(a)&&"Mac OS"==d&&(d=null),a="identify"+a):(a="mask"+a,c=H?E(H.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(a)&&(d=null),x||(e=null)),m=["Presto"],f.push(a));else c+=" Mobile";if(a=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(b)||0)[1]){a=[parseFloat(a.replace(/\.(\d)$/,".0$1")),a];if("Safari"==c&&"+"==a[1].slice(-1))c=
"WebKit Nightly",J="alpha",e=a[1].slice(0,-1);else if(e==a[1]||e==(a[2]=(/\bSafari\/([\d.]+\+?)/i.exec(b)||0)[1]))e=null;a[1]=(/\b(?:Headless)?Chrome\/([\d.]+)/i.exec(b)||0)[1];537.36==a[0]&&537.36==a[2]&&28<=parseFloat(a[1])&&"WebKit"==m&&(m=["Blink"]);x&&(X||a[1])?(m&&(m[1]="like Chrome"),a=a[1]||(a=a[0],530>a?1:532>a?2:532.05>a?3:533>a?4:534.03>a?5:534.07>a?6:534.1>a?7:534.13>a?8:534.16>a?9:534.24>a?10:534.3>a?11:535.01>a?12:535.02>a?"13+":535.07>a?15:535.11>a?16:535.19>a?17:536.05>a?18:536.1>
a?19:537.01>a?20:537.11>a?"21+":537.13>a?23:537.18>a?24:537.24>a?25:537.36>a?26:"Blink"!=m?"27":"28")):(m&&(m[1]="like Safari"),a=(a=a[0],400>a?1:500>a?2:526>a?3:533>a?4:534>a?"4+":535>a?5:537>a?6:538>a?7:601>a?8:602>a?9:604>a?10:606>a?11:608>a?12:"12"));m&&(m[1]+=" "+(a+="number"==typeof a?".x":/[.+]/.test(a)?"":"+"));"Safari"==c&&(!e||45<parseInt(e))?e=a:"Chrome"==c&&/\bHeadlessChrome/i.test(b)&&f.unshift("headless")}"Opera"==c&&(a=/\bzbov|zvav$/.exec(d))?(c+=" ",f.unshift("desktop mode"),"zvav"==
a?(c+="Mini",e=null):c+="Mobile",d=d.replace(RegExp(" *"+a+"$"),"")):"Safari"==c&&/\bChrome\b/.exec(m&&m[1])?(f.unshift("desktop mode"),c="Chrome Mobile",e=null,/\bOS X\b/.test(d)?(n="Apple",d="iOS 4.3+"):d=null):/\bSRWare Iron\b/.test(c)&&!e&&(e=p("Chrome"));e&&0==e.indexOf(a=/[\d.]+$/.exec(d))&&-1<b.indexOf("/"+a+"-")&&(d=K(d.replace(a,"")));d&&-1!=d.indexOf(c)&&!RegExp(c+" OS").test(d)&&(d=d.replace(RegExp(" *"+v(c)+" *"),""));m&&!/\b(?:Avant|Nook)\b/.test(c)&&(/Browser|Lunascape|Maxthon/.test(c)||
"Safari"!=c&&/^iOS/.test(d)&&/\bSafari\b/.test(m[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|SRWare Iron|Vivaldi|Web)/.test(c)&&m[1])&&(a=m[m.length-1])&&f.push(a);f.length&&(f=["("+f.join("; ")+")"]);n&&h&&0>h.indexOf(n)&&f.push("on "+n);h&&f.push((/^on /.test(f[f.length-1])?"":"on ")+h);if(d){var S=(a=/ ([\d.+]+)$/.exec(d))&&"/"==d.charAt(d.length-a[0].length-1);d={architecture:32,family:a&&!S?d.replace(a[0],""):d,version:a?a[1]:null,toString:function(){var q=
this.version;return this.family+(q&&!S?" "+q:"")+(64==this.architecture?" 64-bit":"")}}}(a=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(I))&&!/\bi686\b/i.test(I)?(d&&(d.architecture=64,d.family=d.family.replace(RegExp(" *"+a),"")),c&&(/\bWOW64\b/i.test(b)||x&&/\w(?:86|32)$/.test(C.cpuClass||C.platform)&&!/\bWin64; x64\b/i.test(b))&&f.unshift("32-bit")):d&&/^OS X/.test(d.family)&&"Chrome"==c&&39<=parseFloat(e)&&(d.architecture=64);b||=null;g={};g.description=b;g.layout=m&&m[0];g.manufacturer=n;g.name=c;
g.prerelease=J;g.product=h;g.ua=b;g.version=c&&e;g.os=d||{architecture:null,family:null,version:null,toString:function(){return"null"}};g.parse=F;g.toString=function(){return this.description||""};g.version&&f.unshift(e);g.name&&f.unshift(c);d&&c&&(d!=String(d).split(" ")[0]||d!=c.split(" ")[0]&&!h)&&f.push(h?"("+d+")":"on "+d);f.length&&(g.description=f.join(" "));return g}var B={"function":!0,object:!0},L=B[typeof window]&&window||this,P=B[typeof exports]&&exports;B=B[typeof module]&&module&&!module.nodeType&&
module;var u=P&&B&&"object"==typeof global&&global;!u||u.global!==u&&u.window!==u&&u.self!==u||(L=u);var U=Math.pow(2,53)-1,G=/\bOpera/;u=Object.prototype;var V=u.hasOwnProperty,R=u.toString;sys=F();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(L.platform=platform,define(function(){return platform})):P&&B&&D(platform,function(b,r){P[r]=b})}).call(this);
