function generatePlaywrightSelectors(a){if(!(a&&a instanceof Element))throw Error("Please provide a valid DOM element");const c=[],b=analyzeElementContext(a);generateAllSelectors(a,c,b);c.sort((d,e)=>d.count-e.count);return c}
function countSelectorMatches(a){try{const c=validateSelectorSyntax(a);if(!c.isValid)return console.error("\u274c Selector Syntax Error:",c.error),0;const b=parseSelectorContext(a);let d=navigateToContext(b);if(!d)return 0;const e=extractCleanSelector(a);return executeCount(e,d)}catch(c){return console.error("\u274c Error counting selector matches:",c.message),0}}
function validateSelectorSyntax(a){if(!a.trim().startsWith("page"))return{isValid:!1,error:'Selector must start with "page" (e.g., page.locator(...) or page.getByRole(...))'};const c=[];var b=(a.match(/'/g)||[]).length,d=(a.match(/"/g)||[]).length,e=(a.match(/`/g)||[]).length;0!==b%2&&c.push("Unclosed single quote (')");0!==d%2&&c.push('Unclosed double quote (")');0!==e%2&&c.push("Unclosed backtick (`)");b=(a.match(/\(/g)||[]).length;d=(a.match(/\)/g)||[]).length;b!==d&&c.push(`Mismatched parentheses (${b} open, ${d} close)`);
b=(a.match(/\[/g)||[]).length;d=(a.match(/\]/g)||[]).length;b!==d&&c.push(`Mismatched brackets (${b} open, ${d} close)`);b=(a.match(/\{/g)||[]).length;d=(a.match(/\}/g)||[]).length;b!==d&&c.push(`Mismatched braces (${b} open, ${d} close)`);const f="getByRole getByText getByLabel getByPlaceholder getByAltText getByTitle getByTestId locator frameLocator filter nth first last".split(" ");b=/\.([\w]+)\(/g;for(d=[];null!==(e=b.exec(a));)d.push(e[1]);b=d.filter(g=>!f.includes(g));0<b.length&&c.push(`Invalid Playwright method(s): ${b.join(", ")}`);
if(a.includes("//")||a.includes("//*"))if(b=a.match(/locator\(['"`](.+?)['"`]\)/)||a.match(/locator\(`(.+?)`\)/))if(b=b[1],b.startsWith("//")||b.startsWith("//*"))try{document.evaluate(b,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null)}catch(g){c.push(`Invalid XPath syntax: ${g.message}`)}if(a.includes("locator")&&(b=a.match(/locator\(['"`](.+?)['"`]\)/)||a.match(/locator\(`(.+?)`\)/))&&(b=b[1],!b.startsWith("//")&&!b.startsWith("//*")&&!b.includes(":has-text(")))try{document.querySelector(b)}catch(g){c.push(`Invalid CSS selector: ${g.message}`)}a.includes(".filter(")&&
(a.match(/\.filter\(\s*\{/)||c.push('Invalid filter syntax. Expected: .filter({ hasText: "..." }) or .filter({ has: ... })'));return 0<c.length?{isValid:!1,error:c.join("; ")}:{isValid:!0,error:null}}
function parseSelectorContext(a){const c={iframeSelectors:[],shadowSelectors:[],hasIframe:!1,hasShadow:!1},b=a.matchAll(/frameLocator\('(.+?)'\)/g);for(const d of b)c.iframeSelectors.push(d[1]),c.hasIframe=!0;a=a.matchAll(/\.locator\('(.+?)'\)/g);a=Array.from(a).map(d=>d[1]);1<a.length&&!c.hasIframe&&(c.shadowSelectors=a.slice(0,-1),c.hasShadow=0<c.shadowSelectors.length);return c}
function navigateToContext(a){let c=document;if(a.hasIframe)for(const b of a.iframeSelectors)try{const d=c.querySelector(b);if(!d)return null;c=d.contentDocument||d.contentWindow?.document;if(!c)return null}catch(d){return null}if(a.hasShadow)for(const b of a.shadowSelectors)try{const d=c.querySelector(b);if(!d||!d.shadowRoot)return null;c=d.shadowRoot}catch(d){return null}return c}
function extractCleanSelector(a){a=a.replace(/page\.frameLocator\('.+?'\)\./g,"");a=a.replace(/\.frameLocator\('.+?'\)/g,"");a=a.replace(/^page\./,"");var c=a.match(/(getBy[A-Za-z]+\(.+\))$/);const b=a.match(/locator\((['"`])(.+?)\1\)(?!.*locator)/);if(c)return"page."+c[1];if(b)return"page.locator("+b[1]+b[2]+b[1]+")";c=Array.from(a.matchAll(/locator\((['"`])(.+?)\1\)/g));return 0<c.length?(a=c[c.length-1],"page.locator("+a[1]+a[2]+a[1]+")"):a.startsWith("page.")?a:"page."+a}
function analyzeElementContext(a){const c={isInIframe:!1,iframeChain:[],isInShadowRoot:!1,shadowHosts:[],isSvgElement:!1,rootDocument:a.ownerDocument};"http://www.w3.org/2000/svg"===a.namespaceURI&&(c.isSvgElement=!0);let b=a;for(;b;){const d=b.getRootNode?b.getRootNode():null;d&&d instanceof ShadowRoot?(c.isInShadowRoot=!0,c.shadowHosts.unshift(d.host),b=d.host):b=b.parentElement}for(a=a.ownerDocument?.defaultView;a&&a!==window.top;)try{const d=a.frameElement;d&&(c.isInIframe=!0,c.iframeChain.unshift(d));
a=a.parent}catch(d){break}return c}
function buildSelectorWithContext(a,c){if(c.isInIframe&&0<c.iframeChain.length){let b="page";c.iframeChain.forEach(d=>{let e="iframe";d.id?e=`#${CSS.escape(d.id)}`:d.name?e=`[name="${d.name}"]`:d.title?e=`[title="${d.title}"]`:(d=d.getAttribute("src"))&&(d=d.split("/").pop().split("?")[0])&&(e=`[src*="${d}"]`);b+=`.frameLocator('${e}')`});a=a.replace("page",b)}if(c.isInShadowRoot&&0<c.shadowHosts.length){let b="";c.shadowHosts.forEach(e=>{let f=e.tagName.toLowerCase();e.id?f=`#${CSS.escape(e.id)}`:
e.className&&"string"===typeof e.className&&(e=e.className.trim().split(/\s+/),0<e.length&&(f=`${f}.${CSS.escape(e[0])}`));b+=`.locator('${f}')`});const d=a.replace("page.","").replace("page","");a=c.isInIframe?a.split(/(?=\.frameLocator)/).slice(0,-1).join("")+b+"."+d:"page"+b+"."+d}return a}
function countInContext(a,c){try{let b=document;if(c.isInIframe&&0<c.iframeChain.length){const d=c.iframeChain[c.iframeChain.length-1];b=d.contentDocument||d.contentWindow?.document;if(!b)return 0}return c.isInShadowRoot&&0<c.shadowHosts.length&&(b=c.shadowHosts[c.shadowHosts.length-1].shadowRoot,!b)?0:executeCount(a,b)}catch(b){return 0}}function esc(a){return a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/\n/g," ").replace(/\s+/g," ").trim()}
function executeCount(a,c){if(a.includes("getByTestId")){var b=a.match(/getByTestId\(['"`](.+?)['"`]\)/);if(b)return c.querySelectorAll(`[data-testid="${b[1]}"], [data-test-id="${b[1]}"], [data-test="${b[1]}"], [data-cy="${b[1]}"]`).length}if(a.includes("getByRole")){b=a.match(/getByRole\(['"`](.+?)['"`]/);var d=a.match(/name:\s*['"`\/](.+?)['"`\/]/);if(b)return countByRole(b[1],d?d[1]:null,c)}if(a.includes("getByLabel")&&(b=a.match(/getByLabel\(['"`](.+?)['"`]/),d=a.includes("exact: true"),b))return countByLabel(b[1],
d,c);if(a.includes("getByPlaceholder")&&(b=a.match(/getByPlaceholder\(['"`](.+?)['"`]/)))return c.querySelectorAll(`[placeholder="${b[1]}"]`).length;if(a.includes("getByText")&&(b=a.match(/getByText\(['"`](.+?)['"`]/),d=a.includes("exact: true"),b))return countByText(b[1],d,c);if(a.includes("getByAltText")&&(b=a.match(/getByAltText\(['"`](.+?)['"`]/)))return c.querySelectorAll(`[alt="${b[1]}"]`).length;if(a.includes("getByTitle")&&(b=a.match(/getByTitle\(['"`](.+?)['"`]/)))return c.querySelectorAll(`[title="${b[1]}"]`).length;
if(a.includes(":has-text(")){if(b=a.match(/locator\(['"`](.+?):has-text\(["'](.+?)["']\)['"`]\)/)){const e=b[2];c=c.querySelectorAll(b[1]);return Array.from(c).filter(f=>(f=f.innerText?.trim())&&f.includes(e)).length}if(b=a.match(/locator\(`(.+?):has-text\("(.+?)"\)`\)/)){const e=b[2];c=c.querySelectorAll(b[1]);return Array.from(c).filter(f=>(f=f.innerText?.trim())&&f.includes(e)).length}}if((a.includes("//")||a.includes("//*"))&&(b=a.match(/locator\(['"`](.+?)['"`]\)/)||a.match(/locator\(`(.+?)`\)/))&&
(b[1].startsWith("//")||b[1].startsWith("//*")))try{return c.evaluate(b[1],c,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength}catch(e){return console.error("XPath error:",e),0}if(a.includes("locator")&&(b=a.match(/locator\(['"`](.+?)['"`]\)/)||a.match(/locator\(`(.+?)`\)/)))try{if(!b[1].startsWith("//")&&!b[1].startsWith("//*")&&!b[1].includes(":has-text("))return c.querySelectorAll(b[1]).length}catch(e){return 0}if(a.includes(".filter({ hasText:")){b=a.match(/locator\(['"`](.+?)['"`]\)/);
const e=a.match(/hasText:\s*['"`](.+?)['"`]/);if(b&&e)return c=c.querySelectorAll(b[1]),Array.from(c).filter(f=>f.textContent?.includes(e[1])).length}if(a.includes(".nth(")&&(d=a.match(/locator\(['"`](.+?)['"`]\)/),b=a.match(/\.nth\((\d+)\)/),d&&b))return c=c.querySelectorAll(d[1]).length,parseInt(b[1])<c?1:0;if(a.includes("locator")&&(a=a.match(/locator\(['"`](.+?)['"`]\)/)||a.match(/locator\(`(.+?)`\)/)))try{return c.querySelectorAll(a[1]).length}catch(e){}return 0}
function countByRole(a,c,b){return Array.from(b.querySelectorAll("*")).filter(d=>(d.getAttribute("role")||getImplicitRole(d))!==a?!1:c?(d=getAccessibleName(d))&&d.includes(c):!0).length}
function countByLabel(a,c,b){let d=0;b.querySelectorAll("label").forEach(e=>{const f=e.textContent?.trim();if(c?f===a:f?.includes(a))e.htmlFor&&b.getElementById(e.htmlFor)?d++:e.querySelector("input, select, textarea")&&d++});b.querySelectorAll("[aria-label]").forEach(e=>{e=e.getAttribute("aria-label");(c?e===a:e?.includes(a))&&d++});return d}
function countByText(a,c,b){return Array.from(b.querySelectorAll("*")).filter(d=>{if(!Array.from(d.childNodes).some(e=>3===e.nodeType&&e.textContent.trim())&&0<d.children.length)return!1;d=d.textContent?.trim();return c?d===a:d?.includes(a)}).length}
function getImplicitRole(a){const c=a.tagName.toLowerCase(),b=a.type;return{button:"button",a:a.href?"link":null,input:"button"===b||"submit"===b?"button":"checkbox"===b?"checkbox":"radio"===b?"radio":"textbox",textarea:"textbox",select:"combobox",img:"img",h1:"heading",h2:"heading",h3:"heading",h4:"heading",h5:"heading",h6:"heading"}[c]||null}
function getAccessibleName(a){if(a.getAttribute("aria-label"))return a.getAttribute("aria-label");if(a.id){const c=document.querySelector(`label[for="${a.id}"]`);if(c)return c.textContent?.trim()}return a.alt?a.alt:["button","a"].includes(a.tagName.toLowerCase())?a.textContent?.trim():a.placeholder?a.placeholder:null}
function generateXPath(a,c){c=a.tagName.toLowerCase();if(a.id)return`//*[@id="${a.id}"]`;if(a.name)return`//${c}[@name="${a.name}"]`;for(c=[];a&&a.nodeType===Node.ELEMENT_NODE;){let d=0;for(var b=a.previousSibling;b;)b.nodeType===Node.ELEMENT_NODE&&b.nodeName===a.nodeName&&d++,b=b.previousSibling;b=a.nodeName.toLowerCase();c.unshift(0<d?`${b}[${d+1}]`:b);a=a.parentNode;if("body"===b)break}return"//"+c.join("/")}
function esc(a){return a.replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/\n/g," ").replace(/\s+/g," ").trim()}
function generateAllSelectors(a,c,b){const d=h=>{const k=countInContext(h,b);0<k&&c.push({selector:buildSelectorWithContext(h,b),count:k})};["data-testid","data-test-id","data-test","data-cy"].some(h=>{if(a.hasAttribute(h))return d(`page.getByTestId('${esc(a.getAttribute(h))}')`),!0});var e=a.getAttribute("role")||getImplicitRole(a);if(e){var f=getAccessibleName(a);f&&100>f.length&&(d(`page.getByRole('${e}', { name: '${esc(f)}' })`),d(`page.getByRole('${e}', { name: /${f.replace(/[.*+?^${}()|[\]\\]/g,
"\\$&")}/i })`));d(`page.getByRole('${e}')`)}e=null;a.id&&(f=b.rootDocument.querySelector(`label[for="${a.id}"]`))&&(e=f.textContent?.trim());e||(f=a.closest("label"))&&(e=f.textContent?.trim());!e&&a.getAttribute("aria-label")&&(e=a.getAttribute("aria-label"));e&&100>e.length&&(d(`page.getByLabel('${esc(e)}')`),d(`page.getByLabel('${esc(e)}', { exact: true })`));a.placeholder&&100>a.placeholder.length&&(d(`page.getByPlaceholder('${esc(a.placeholder)}')`),d(`page.getByPlaceholder('${esc(a.placeholder)}', { exact: true })`));
(f=(a.innerText||a.textContent)?.trim())&&0<f.length&&100>f.length&&(d(`page.getByText('${esc(f)}', { exact: true })`),d(`page.getByText('${esc(f)}')`),d(`page.locator(\'${a.tagName.toLowerCase()}:has-text("${esc(f)}")\')`));a.alt&&100>a.alt.length&&(d(`page.getByAltText('${esc(a.alt)}')`),d(`page.getByAltText('${esc(a.alt)}', { exact: true })`));a.title&&100>a.title.length&&(d(`page.getByTitle('${esc(a.title)}')`),d(`page.getByTitle('${esc(a.title)}', { exact: true })`));e=a.tagName.toLowerCase();
a.id&&d(`page.locator('#${CSS.escape(a.id)}')`);a.name&&(d(`page.locator('[name="${a.name}"]')`),d(`page.locator('${e}[name="${a.name}"]')`));if(a.className&&"string"===typeof a.className){var g=a.className.trim().split(/\s+/).filter(h=>h);if(0<g.length){const h="."+g.map(k=>CSS.escape(k)).join(".");d(`page.locator('${e}${h}')`);1===g.length&&d(`page.locator('${h}')`)}}a.type&&"input"===e&&d(`page.locator('input[type="${a.type}"]')`);b.isSvgElement&&(a.id&&d(`page.locator('svg #${CSS.escape(a.id)}')`),
a.className?.baseVal&&(g=a.className.baseVal.trim().split(/\s+/).filter(h=>h),0<g.length&&(g="."+g.map(h=>CSS.escape(h)).join("."),d(`page.locator('svg ${e}${g}')`))),["data-icon","data-name","aria-label"].forEach(h=>{a.hasAttribute(h)&&d(`page.locator('svg [${h}="${a.getAttribute(h)}"]')`)}),f&&50>f.length&&d(`page.locator('svg ${e}:has-text("${esc(f)}")')`));f&&100>f.length&&d(`page.locator('${e}').filter({ hasText: '${esc(f)}' })`);a.parentElement&&(f=Array.from(a.parentElement.children).indexOf(a),
0<=f&&d(`page.locator('${e}').nth(${f})`))}function analyzeElement(a){const c=analyzeElementContext(a);c.isInIframe&&c.iframeChain.forEach((b,d)=>{});c.isInShadowRoot&&c.shadowHosts.forEach((b,d)=>{b.tagName.toLowerCase()});a=generatePlaywrightSelectors(a);displaySelectors(a);return a}function getBest(a){return generatePlaywrightSelectors(a)[0]||null}function getUnique(a){return generatePlaywrightSelectors(a).filter(c=>1===c.count)}
function getSelectorMatches(a){try{const c=parseSelectorContext(a);let b=navigateToContext(c);if(!b)return[];const d=extractCleanSelector(a);return executeGetElements(d,b)}catch(c){return console.error("Error getting selector matches:",c.message),[]}}
function executeGetElements(a,c){if(a.includes("getByTestId")){var b=a.match(/getByTestId\(['"`](.+?)['"`]\)/);if(b)return Array.from(c.querySelectorAll(`[data-testid="${b[1]}"], [data-test-id="${b[1]}"], [data-test="${b[1]}"], [data-cy="${b[1]}"]`))}if(a.includes("getByRole")){b=a.match(/getByRole\(['"`](.+?)['"`]/);var d=a.match(/name:\s*['"`\/](.+?)['"`\/]/);if(b)return findByRole(b[1],d?d[1]:null,c)}if(a.includes("getByLabel")&&(b=a.match(/getByLabel\(['"`](.+?)['"`]/),d=a.includes("exact: true"),
b))return findByLabel(b[1],d,c);if(a.includes("getByPlaceholder")&&(b=a.match(/getByPlaceholder\(['"`](.+?)['"`]/)))return Array.from(c.querySelectorAll(`[placeholder="${b[1]}"]`));if(a.includes("getByText")&&(b=a.match(/getByText\(['"`](.+?)['"`]/),d=a.includes("exact: true"),b))return findByText(b[1],d,c);if(a.includes("getByAltText")&&(b=a.match(/getByAltText\(['"`](.+?)['"`]/)))return Array.from(c.querySelectorAll(`[alt="${b[1]}"]`));if(a.includes("getByTitle")&&(b=a.match(/getByTitle\(['"`](.+?)['"`]/)))return Array.from(c.querySelectorAll(`[title="${b[1]}"]`));
if(a.includes(":has-text(")){if(b=a.match(/locator\(['"`](.+?):has-text\(["'](.+?)["']\)['"`]\)/)){const f=b[2];c=c.querySelectorAll(b[1]);return Array.from(c).filter(g=>(g=g.innerText?.trim())&&g.includes(f))}if(b=a.match(/locator\(`(.+?):has-text\("(.+?)"\)`\)/)){const f=b[2];c=c.querySelectorAll(b[1]);return Array.from(c).filter(g=>(g=g.innerText?.trim())&&g.includes(f))}}if((a.includes("//")||a.includes("//*"))&&(b=a.match(/locator\(['"`](.+?)['"`]\)/)||a.match(/locator\(`(.+?)`\)/))&&(b[1].startsWith("//")||
b[1].startsWith("//*")))try{var e=c.evaluate(b[1],c,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);c=[];for(a=0;a<e.snapshotLength;a++)c.push(e.snapshotItem(a));return c}catch(f){return console.error("XPath error:",f),[]}if(a.includes("locator")&&(e=a.match(/locator\(['"`](.+?)['"`]\)/)||a.match(/locator\(`(.+?)`\)/)))try{if(!e[1].startsWith("//")&&!e[1].startsWith("//*"))return Array.from(c.querySelectorAll(e[1]))}catch(f){return[]}if(a.includes(".filter({ hasText:")&&(b=a.match(/locator\(['"`](.+?)['"`]\)/),
e=a.match(/hasText:\s*['"`](.+?)['"`]/),b&&e)){c=c.querySelectorAll(b[1]);const f=e[1];return Array.from(c).filter(g=>(g=g.innerText)?g.includes(f):!1)}if(a.includes(".filter({ has:")&&(b=a.match(/locator\(['"`](.+?)['"`]\)/),e=a.match(/has:\s*page\.locator\(['"`](.+?)['"`]\)/),b&&e)){c=c.querySelectorAll(b[1]);const f=e[1];return Array.from(c).filter(g=>{try{return null!==g.querySelector(f)}catch(h){return!1}})}if(a.includes(".nth(")&&(b=a.match(/locator\(['"`](.+?)['"`]\)/),e=a.match(/\.nth\((\d+)\)/),
b&&e))return c=Array.from(c.querySelectorAll(b[1])),a=parseInt(e[1]),a<c.length?[c[a]]:[];if(a.includes("locator")&&(a=a.match(/locator\(['"`](.+?)['"`]\)/)||a.match(/locator\(`(.+?)`\)/)))try{return Array.from(c.querySelectorAll(a[1]))}catch(f){}return[]}function findByRole(a,c,b){return Array.from(b.querySelectorAll("*")).filter(d=>(d.getAttribute("role")||getImplicitRole(d))!==a?!1:c?(d=getAccessibleName(d))&&d.includes(c):!0)}
function findByLabel(a,c,b){const d=[];b.querySelectorAll("label").forEach(e=>{const f=e.textContent?.trim();if(c?f===a:f?.includes(a))e.htmlFor?(e=b.getElementById(e.htmlFor))&&d.push(e):(e=e.querySelector("input, select, textarea"))&&d.push(e)});b.querySelectorAll("[aria-label]").forEach(e=>{const f=e.getAttribute("aria-label");(c?f===a:f?.includes(a))&&!d.includes(e)&&d.push(e)});return d}
function findByText(a,c,b){return Array.from(b.querySelectorAll("*")).filter(d=>{if(!Array.from(d.childNodes).some(e=>3===e.nodeType&&e.textContent.trim())&&0<d.children.length)return!1;d=d.textContent?.trim();return c?d===a:d?.includes(a)})}
function testSelector(a){a=getSelectorMatches(a);0<a.length&&a.slice(0,5).forEach((c,b)=>{c.tagName.toLowerCase();c.className&&"string"===typeof c.className&&c.className.split(" ").filter(d=>d).slice(0,2).join(".");c.textContent?.trim().substring(0,30)});return a}
function inspectMatches(a){a=getSelectorMatches(a);if(0===a.length)return a;a.forEach((c,b)=>{c.textContent?.trim();b="data-testid data-test aria-label placeholder alt title href".split(" ").filter(d=>c.hasAttribute(d));0<b.length&&b.forEach(d=>{})});return a};
