var devtoolsRegEx=/^chrome-devtools:\/\//,connections={},clickEnabled=!0,master={},API=chrome||browserType,contentWindowId="",isFirefox="undefined"!==typeof InstallTrigger;const options={active:!0,currentWindow:!0};var browserType=chrome;const state={contextMenusCreated:!1},API_URL="https://shubads.testcasehub.net/",EXT_ID="3";let isEdge=-1<navigator.userAgent.indexOf("Edg/")?!0:!1,isChrome=!!chrome&&(!!chrome.webstore||!!chrome.runtime),isOpera=0<=navigator.userAgent.indexOf(" OPR/"),platform="chrome";
isChrome&&(platform="chrome");isFirefox&&(platform="firefox");isEdge&&(platform="edge");isOpera&&(platform="opera");let countryName=null;Intl&&(Intl.DateTimeFormat().resolvedOptions().timeZone.split("/"),countryName="");async function getCurrentTab(){let [a]=await chrome.tabs.query({active:!0,lastFocusedWindow:!0});return a.id}function trackEvent(a){"string"!==typeof a&&fetch(`${API_URL}analytics/ads/track`,{method:"post",headers:{"Content-Type":"application/json"},body:JSON.stringify(a)})}
const createContextMenus=()=>{state.contextMenusCreated||(browserType.contextMenus.create({id:"mouseOver",title:"Mouse Over",documentUrlPatterns:["<all_urls>"],contexts:["all"]}),browserType.contextMenus.create({id:"separator-1",type:"separator",documentUrlPatterns:["<all_urls>"],contexts:["all"]}),browserType.contextMenus.create({id:"assert",title:"Assert",documentUrlPatterns:["<all_urls>"],contexts:["all"]}),browserType.contextMenus.create({id:"store",title:"Store",documentUrlPatterns:["<all_urls>"],
contexts:["all"]}),browserType.contextMenus.create({id:"verify",title:"Verify",documentUrlPatterns:["<all_urls>"],contexts:["all"]}),browserType.contextMenus.create({id:"waitFor",title:"Wait For",documentUrlPatterns:["<all_urls>"],contexts:["all"]}),[{items:[{id:"assertChecked",title:"Checked"},{id:"assertEditable",title:"Editable"},{id:"assertNotChecked",title:"Not Checked"},{id:"assertNotEditable",title:"Not Editable"},{id:"assertElementNotPresent",title:"Not Present"},{id:"assertNotSelectedValue",
title:"Not Selected Value"},{id:"assertNotText",title:"Not Text"},{id:"assertElementPresent",title:"Present"},{id:"assertSelectedLabel",title:"Selected Label"},{id:"assertSelectedValue",title:"Selected Value"},{id:"assertText",title:"Text"},{id:"assertTitle",title:"Title"},{id:"assertValue",title:"Value"}],parent:"assert"},{items:[{id:"storeText",title:"Text"},{id:"storeTitle",title:"Title"},{id:"storeValue",title:"Value"}],parent:"store"},{items:[{id:"verifyChecked",title:"Checked"},{id:"verifyEditable",
title:"Editable"},{id:"verifyNotChecked",title:"Not Checked"},{id:"verifyNotEditable",title:"Not Editable"},{id:"verifyElementNotPresent",title:"Not Present"},{id:"verifyNotSelectedValue",title:"Not Selected Value"},{id:"verifyNotText",title:"Not Text"},{id:"verifyElementPresent",title:"Present"},{id:"verifySelectedLabel",title:"Selected Label"},{id:"verifySelectedValue",title:"Selected Value"},{id:"verifyText",title:"Text"},{id:"verifyTitle",title:"Title"},{id:"verifyValue",title:"Value"}],parent:"verify"},
{items:[{id:"waitForElementEditable",title:"Editable"},{id:"waitForElementNotEditable",title:"Not Editable"},{id:"waitForElementNotPresent",title:"Not Present"},{id:"waitForElementNotVisible",title:"Not Visible"},{id:"waitForElementPresent",title:"Present"},{id:"waitForElementVisible",title:"Visible"},{id:"waitForText",title:"Text"}],parent:"waitFor"}].forEach(({items:a,parent:c})=>{a.forEach(b=>{browserType.contextMenus.create({id:b.id,title:b.title,documentUrlPatterns:["<all_urls>"],contexts:["all"],
parentId:c})})}),state.contextMenusCreated=!0)},removeContextMenus=()=>{state.contextMenusCreated&&chrome.contextMenus.removeAll(()=>{state.contextMenusCreated=!1})};
browserType.contextMenus.onClicked.addListener((a,c)=>{c.id&&(["assert","store","verify","waitFor"].includes(a.menuItemId)?browserType.tabs.sendMessage(c.id,{action:"context-menu-clicked",menuItemId:a.menuItemId,menuItemParentId:""}):"mouseOver"===a.menuItemId?browserType.tabs.sendMessage(c.id,{action:"context-menu-clicked",menuItemId:a.menuItemId,menuItemParentId:""}):browserType.tabs.sendMessage(c.id,{action:"context-menu-clicked",menuItemId:a.menuItemId,menuItemParentId:a.parentMenuItemId}))});
browserType.runtime.onMessage.addListener((a,c,b)=>{a.action&&("recording-started"===a.action?createContextMenus():"recording-stopped"===a.action&&removeContextMenus());"focuse_tcs_window"===a.name&&browserType.windows.update(contentWindowId,{focused:!0});"limit reached"==a.message&&browserType.tabs.query(options,d=>{browserType.tabs.sendMessage(d[0].id,{message:"limit reached"})});"take screenshoot"==a.message&&setTimeout(function(){browserType.tabs.captureVisibleTab(null,{format:"jpeg",quality:25},
function(d){b({imgSrc:d})})},100);a&&"AttachStudio"===a.message&&(clickEnabled=!1);a&&"DeattachStudio"===a.message&&(clickEnabled=!0);if(c.tab)if(devtoolsRegEx.test(c.tab.url)){if("shown"===a.event||"hidden"===a.event)c=c.tab.id,c in connections&&connections[c].postMessage(a);messageToContentScript(a)}else c=c.tab.id,c in connections&&connections[c].postMessage(a);return!0});var messageToContentScript=function(a){browserType.tabs.sendMessage(a.tabId,a)};
browserType.runtime.onConnect.addListener(function(a){var c=function(b,d,e){b&&"DeattachStudio"===b.message&&(clickEnabled=!0);"init"==b.name?connections[b.tabId]=a:"active"==b.name?window.browserType.windows.update(contentWindowId,{focused:!0}):"openStudio"==b.name?clickEnabled?openStudioWindow():window.browserType.windows.update(contentWindowId,{focused:!0}):messageToContentScript(b)};a.onMessage.addListener(c);a.onDisconnect.addListener(function(b){b.onMessage.removeListener(c);for(var d=Object.keys(connections),
e=0,f=d.length;e<f;e++)if(connections[d[e]]==b){delete connections[d[e]];break}})});var installURL="https://www.youtube.com/playlist?list=PLmRg3gEG2XIZVUSNshlflDIYFUrD9-xr0",updateURL="https://selectorshub.com/testcase-studio/",uninstallURL="https://selectorshub.com/testcase-studio/uninstall-tcs/";
const manifest=browserType.runtime.getManifest(),generateExtensionUniqueId=a=>{let c="";for(let b=0;b<a;b++)c+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return"sh_"+c};var onUpdateLink="https://bit.ly/3YciC1d";function onClickNotification(){chrome.tabs.create({url:onUpdateLink})}function openLink(a){browserType.tabs.create({url:a})}function onClickInstallNoti(){browserType.tabs.create({url:installURL})}
function onClickNoti(){browserType.tabs.create({url:updateURL})}
function updateNotification(){let a,c="";fetch(`${API_URL}ad?published=true&extensions=5&mode=ext__ads&browsers=${platform}&fe=true`).then(b=>b.json()).then(b=>{0<b.ads.length&&b.ads[0].link&&(a=b.ads[0].ad,c=b.ads[0].company_name.toUpperCase(),onUpdateLink=b.ads[0].link,b=c.toLowerCase()+".png",chrome.notifications.create("my-notification",{title:c,message:a,iconUrl:b,type:"basic"},function(d){console.log("Last error:",chrome.runtime.lastError)}))})}
const installNotification=()=>{browserType.notifications.create("onInstalled",{title:"TestCase Studio",message:"Refresh the opened tab & watch the video tutorial to make best use of TestCase Studio",type:"basic",iconUrl:"logo-128.png"})};
function openStudioWindow(){browserType.windows.create({url:API.runtime.getURL("testCaseStudio/studioWindow.html"),type:"popup",height:602,width:1350}).then(function(a){master[a.id]=a;contentWindowId=a.id;browserType.tabs.sendMessage(contentWindowId,{type:"studioId",studioId:a});browserType.tabs.query({active:!0,windowId:a.id,status:"complete"}).then(function(c){1!=c.length&&(master[a.id]=a.id)})}).catch(function(a){})}
browserType.action.onClicked.addListener(function(a){if(clickEnabled){openStudioWindow();a=Math.floor(Date.now()/1E3)+63072E3;var c=!1;browserType.cookies.getAll({},function(b){for(const d of b)"selectorshub-tcs"==d.name&&(c=!0)});c||browserType.cookies.set({url:"https://testrigor.com",name:"selectorshub-tcs",value:"selectorshub-tcs",secure:!0,expirationDate:a})}else browserType.windows.update(contentWindowId,{focused:!0})});
const newAPiUrl="https://selectorshub.info/nodeapp/api/",EXT_SLUG="TCS",installedListener2=async a=>{let c="";try{if("install"===a.reason){c="on_install";const b=await (await fetch(`${newAPiUrl}link-ads?type=${c}&extension=${EXT_SLUG}&browsers=${platform}`)).json();Array.isArray(b[c])&&b[c].forEach(d=>openLink(d));Array.isArray(b.on_uninstall)&&0<b.on_uninstall.length&&browserType.runtime.setUninstallURL(b.on_uninstall[0])}else"update"===a.reason&&browserType.storage.local.get(["ttlt"],async b=>{if("undefined"==
typeof b.ttlt||"undefined"==b.ttlt||null==b.ttlt||""==b.ttlt)c="on_update",b=await (await fetch(`${newAPiUrl}link-ads?type=${c}&extension=${EXT_SLUG}&browsers=${platform}`)).json(),Array.isArray(b[c])&&(b[c].forEach(d=>openLink(d)),onUpdateLink=b[c],chrome.notifications.onClicked.addListener(onClickNotification)),Array.isArray(b.on_uninstall)&&0<b.on_uninstall.length&&browserType.runtime.setUninstallURL(b.on_uninstall[0])})}catch(b){console.error(`Error during ${c} fetch:`,b)}};browserType.runtime.onInstalled.addListener(installedListener2);
