var idAttr=document.querySelector(".id"),classAttr=document.querySelector(".class"),nameAttr=document.querySelector(".name"),placeholder=document.querySelector(".placeholder"),textXpath=document.querySelector(".textXpath"),checkboxes=document.querySelectorAll(".chooseAttr"),tablePlaceholder=document.querySelector(".tablePlaceholder"),copyAllSteps=document.querySelector(".copyAllButton"),copyAllData=document.querySelector(".copyAllData"),copyAllExpRes=document.querySelector(".copyAllExpRes"),copyAllXpath=
document.querySelector(".copyAllXpath"),copyAllCss=document.querySelector(".copyAllCss"),fileName=document.querySelector("#downloadFileName input"),recordButton=document.getElementById("record"),recordIcon=document.getElementById("recordIcon"),element=document.getElementById("records-grid"),helperText=document.getElementById("helperText"),save_btn=document.getElementById("save_btn"),toggleElement=document.getElementById("inputToggle"),xpathInput=document.getElementById("xpathInput"),clearTestCase=
document.getElementById("clearTestCase"),alwaysTop=document.getElementById("alwaysTop"),pauseBtnToolTip=document.querySelector(".pauseBtn.toolTip"),toggleToolTip=document.querySelector(".toggle.toolTip");let platform="";var email=document.getElementById("email"),pass=document.getElementById("password"),company=document.getElementById("company"),registerBtn=document.getElementById("submit_btn"),spanLogin=document.getElementById("login");let authenticated=!1;var screenToggler=document.getElementById("screenshotToggle");
screenToggler.classList.add("active");screenToggler.classList.remove("inactive");let screenshootEnabled=!0,screenDataColumnChecked=!0,isthereAnImage=!1,actualImage,stepsArray=[];var OS=window.navigator.userAgent.includes("Mac")?"mac":"windows";let imagesArray=[],limitReached=!1,countryName=null;if(Intl){let a=Intl.DateTimeFormat().resolvedOptions().timeZone.split("/");countryName=COUNTRIES[a[a.length-1]]}
var isOpera=!!window.opr&&!!opr.addons||!!window.opera||0<=navigator.userAgent.indexOf(" OPR/"),isFirefox="undefined"!==typeof InstallTrigger,isSafari=/constructor/i.test(window.HTMLElement)||function(a){return"[object SafariRemoteNotification]"===a.toString()}(!window.safari||"undefined"!==typeof safari&&safari.pushNotification),isEdge=-1<window.navigator.userAgent.indexOf("Edg/")?!0:!1,isChrome=!!window.chrome&&(!!window.chrome.webstore||!!window.chrome.runtime),reviewLink=document.querySelector(".review-link"),
browserType=chrome,modal=document.getElementById("myModal"),modalImg=document.getElementById("img01");isChrome&&(platform="chrome");isFirefox&&(reviewLink.setAttribute("href","https://addons.mozilla.org/en-US/firefox/addon/testcase-studio/"),browserType=chrome,platform="firefox");isOpera&&(reviewLink.setAttribute("href","https://addons.opera.com/en-gb/extensions/details/testcase-studio/"),platform="opera");isEdge&&(platform="edge",reviewLink.setAttribute("href","https://microsoftedge.microsoft.com/addons/detail/testcase-studio/jdglgpgchkgiciogpolofelfdfkdgfcg"));
const API_URL="https://shubads.testcasehub.net/",EXT_ID="3",TOP_EXT_ID="https://shubads.testcasehub.net/"===API_URL?"11":"6",OFFER_EXT_ID="https://shubads.testcasehub.net/"===API_URL?"14":"9",newAPiUrl="https://selectorshub.info/nodeapp/api/",EXT_SLUG="TCS",TOP_EXT_SLUG="TCST",OFFER_EXT_SLUG="OFT";var recording=!0,steps=[],xpathText="",senderId="",attrArr="[, withid,withclass,withname,withplaceholder,withtext]",interval=null,userEmail="Anonymous";
let systemInfoContainer=document.querySelector("#system-information th"),systemInfoCopyBtn=document.querySelector(".copy-sys-info"),timezone="UTC",now="";const monthNames="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");let os={};
function displaySystemInformation(){now=new Date;timezone=now.toLocaleDateString(void 0,{day:"2-digit",timeZoneName:"short"}).substring(4);systemInfoContainer.innerHTML+=`<span>OS: </span> ${os.platform||""} ${os.version||""} <span class="dividor">|</span> <span>Browser: </span> ${sys.name||""} ${sys.version.split(".")[0]||""} <span class="dividor">|</span> <span>Resolution: </span> ${window.screen.availWidth}x${window.screen.availHeight} <span class="dividor">|</span> <span>Time: </span> ${now.getDate()} ${monthNames[now.getMonth()]} ${now.getFullYear()} / ${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}  ${timezone}`}
navigator.userAgentData.getHighEntropyValues(["platformVersion"]).then(a=>{if(a)if("Windows"===navigator.userAgentData.platform){const b=parseInt(a.platformVersion.split(".")[0]);13<=b?(os.platform=a.platform,os.version=11):0<b?(os.platform=a.platform,os.version=10):(os.platform=sys.os.family,os.version=sys.os.version)}else os.platform=a.platform,os.version=a.platformVersion;else os.platform=sys.os.family,os.version=sys.os.version;displaySystemInformation()});
systemInfoCopyBtn.addEventListener("click",()=>{navigator.clipboard.writeText(`OS: ${os.platform||""} ${os.version||""} | Browser: ${sys.name||""} ${sys.version.split(".")[0]||""} | Resolution: ${window.screen.availWidth}x${window.screen.availHeight} | Time: ${now.getDate()} ${monthNames[now.getMonth()]} ${now.getFullYear()} / ${now.getHours()}:${now.getMinutes()}:${now.getSeconds()}  ${timezone}`);systemInfoCopyBtn.children[0].classList.remove("hideElement");setTimeout(()=>{systemInfoCopyBtn.children[0].classList.add("hideElement")},
300)});let queue=[];
const removeStep=a=>{if(!(0>a)){a=steps.length-1;var b=steps[a-1];(b.step.startsWith("Right click on")||b.step.startsWith("then the user right click"))&&steps.splice(a-1,1);displayRows()}},newStep=(a,b)=>{screenshootEnabled&&0!==a.data.indexOf("Press Enter")?chrome.runtime.sendMessage({message:"take screenshoot"},async c=>{let f=await browserType.storage.local.get(["recorderCommands"]);queue.forEach(d=>{0!==d.data.indexOf("Press Enter")?(steps.length||steps.push({step:f.recorderCommands.openWebsite.sentence||"Open website",
relXpath:"",relCss:"",dataText:d.URL,planeLabel:d.URL,passwordValue:"",expRes:"",screenImage:c.imgSrc}),steps.push({step:d.data,relXpath:d.relXpath,relCss:d.relCss,dataText:d.dataText,passwordValue:d.passwordValue,planeLabel:d.planeLabel,expRes:"",screenImage:c.imgSrc})):(steps.length||steps.push({step:f.recorderCommands.openWebsite.sentence||"Open website",relXpath:"",relCss:"",dataText:d.URL,passwordValue:"",planeLabel:d.URL,expRes:""}),steps.push({step:d.data,relXpath:d.relXpath,relCss:d.relCss,
dataText:d.dataText,passwordValue:d.passwordValue,planeLabel:d.planeLabel,expRes:""}));"contextMenu"===d.command&&removeStep(steps.length-1);authenticated&&displayRows();b({msg:"done"})});queue=[]}):queue[0]===a&&(steps.length||steps.push({step:"Open website",relXpath:"",relCss:"",dataText:a.URL,passwordValue:"",planeLabel:a.URL,expRes:""}),steps.push({step:a.data,relXpath:a.relXpath,relCss:a.relCss,dataText:a.dataText,passwordValue:a.passwordValue,planeLabel:a.planeLabel,expRes:""}),"contextMenu"===
a.command&&removeStep(steps.length-1),authenticated&&displayRows(),b({msg:"done"}),queue.shift())};
chrome.runtime.onMessage.addListener(async function(a,b,c){senderId=b.tab&&b.tab.id;a&&"windowEvent"===a.type&&recording&&"Click on aTag"!==a.data&&(queue.push(a),browserType.storage.local.get(["screenDataColumn"],function(f){"checked"==f.screenDataColumn&&(screenDataColumnChecked=!0)}),newStep(a,c));a&&"recorderAttr"===a.type&&setAttr(a.data);a&&"verification"===a.type&&recording&&senderId&&browserType.tabs.sendMessage(senderId,{openStudio:!0})});
var dataDisplay,expResultDisplay,xpathDisplay,cssDisplay="";function safeDisplay(a){a=a.replace(/</,"&lt;");a=a.replace(/>/,"&gt;");a=a.replace("/","&#x2F;");a=a.replace("[","&#91;");a=a.replace("]","&#93;");return a=a.replace("'","&#39;")}
function displayRows(){element.innerHTML=null;document.querySelector(".tablePlaceholder").style.display="none";var a=!!toggleElement.classList.contains("active");dataDisplay=dataColumnCheckbox.checked?"":"dataDisplay";expResultDisplay=expResultColumnCheckbox.checked?"":"expResultDisplay";xpathDisplay=xpathColumnCheckbox.checked?"":"xpathDisplay";cssDisplay=cssSelectorColumnCheckbox.checked?"":"cssDisplay";if(steps&&steps.length){50!=steps.length||limitReached||(chrome.runtime.sendMessage({message:"limit reached"}),
limitReached=!0);command="";cssCommand="";if(a&&xpathInput.value&&xpathInput.value.toLowerCase().includes("xpathvalue"))for(let c=0;c<steps.length;c++){var b=cssCommand=a=command="";let f=!1;steps[c].relXpath&&steps[c].relXpath.length&&(command=xpathInput.value.replace(/xpathvalue/i,steps[c].relXpath),a=xpathInput.value.replace(/xpathvalue/i,`${steps[c].relXpath}`));steps[c].relCss&&steps[c].relCss.length&&(cssCommand=xpathInput.value.replace(/xpathvalue/i,steps[c].relCss),b=xpathInput.value.replace(/xpathvalue/i,
`${steps[c].relCss}`),b=b.includes("By.xpath")?b.replace("By.xpath","By.cssSelector"):b.includes("By(xpath")?b.replace("By(xpath","By(cssSelector"):b.includes("ByXPath")?b.replace("ByXPath","ByCssSelector"):b.includes("cy.xpath")?b.replace("cy.xpath","cy.get"):b.replace("cy.Xpath","cy.get"));xpathInput.value&&xpathInput.value.toLowerCase().includes("labelvalue")&&(f=!0);element.innerHTML=screenDataColumnChecked?element.innerHTML+`
                <tr class="tableRow">
                    <td class='fixedColumns'>
                        <div class='tableData index'>${c+1}</div>
                    </td>
                    <td class='stepColumn'>
                        <div title="${safeDisplay(steps[c].step)}" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class='tableData allSteps'>${safeDisplay(steps[c].step)}</div>
                    </td>
                    <td title="${steps[c].dataText}" class='dataColumn ${dataDisplay}'>
                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class='tableData dataCol'>${steps[c].dataText}</div>
                    </td>
                    <td class='expResColumn ${expResultDisplay}'>
                        <div class="tableData expRes" autocomplete="off"  autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" title="enter your expected result here">${steps[c].expRes}</div>
                    </td>
                    <td class='xpathColumn ${xpathDisplay}'>
                       <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" title="${command}" class="tableData xpathData">${a}</div>
                    </td>
                    <td class='cssColumn ${cssDisplay}'>
                       <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class="tableData cssData">${b}</div>
                    </td>
                     <td class='screenshotColumn'>
                       <button  class='btn_screen' > <img class='screens' src='${steps[c].screenImage}' alt='undefined'  ></button> 
                    </td>
                    <td class="actionCol">
                        <button id='addStep'></button>
                        <button id='delButton'></button>
                    </td>
                </tr>
                `:element.innerHTML+`
                <tr class="tableRow">
                    <td class='fixedColumns'>
                        <div class='tableData'>${c+1}</div>
                    </td>
                    <td class='stepColumn'>
                        <div title="${safeDisplay(steps[c].step)}" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class='tableData allSteps'>${safeDisplay(steps[c].step)}</div>
                    </td>
                    <td title="${steps[c].dataText}" class='dataColumn ${dataDisplay}'>
                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class='tableData dataCol'>${steps[c].dataText}</div>
                    </td>
                    <td class='expResColumn ${expResultDisplay}'>
                        <div class="tableData expRes" autocomplete="off"  autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" title="enter your expected result here">${steps[c].expRes}</div>
                    </td>
                    <td class='xpathColumn ${xpathDisplay}'>
                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" title="${command}" class="tableData xpathData">${a}</div>
                    </td>
                    <td class='cssColumn ${cssDisplay}'>
                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class="tableData cssData">${b}</div>
                    </td>
                    <td class="actionCol">
                        <button id='addStep'></button>
                        <button id='delButton'></button>
                    </td>
                </tr>
                `;f&&(document.querySelector(`#label-${c}`).textContent=a.replace(/labelvalue/i,toCamelCase(steps[c].planeLabel)))}else for(a=0;a<steps.length;a++)element.innerHTML=screenDataColumnChecked?element.innerHTML+`
                <tr class="tableRow">
                    <td class='fixedColumns'>
                        <div class='tableData'>${a+1}</div>
                    </td>
                    <td class='stepColumn'>
                        <div title="${safeDisplay(steps[a].step)}" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class='tableData allSteps'>${safeDisplay(steps[a].step)}</div>
                    </td>
                    <td title="${steps[a].dataText}" class='dataColumn ${dataDisplay}'>
                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class='tableData dataCol'>${steps[a].dataText}</div>
                    </td>
                    <td class='expResColumn ${expResultDisplay}'>
                        <div class="tableData expRes" autocomplete="off"  autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" title="enter your expected result here">${steps[a].expRes}</div>
                    </td>
                    <td class='xpathColumn ${xpathDisplay}'>
                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" title="${steps[a].relXpath}" class="tableData xpathData xpathColor">${steps[a].relXpath}</div>
                    </td>
                    <td class='cssColumn ${cssDisplay}'>
                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class="tableData cssData xpathColor">${steps[a].relCss}</div>
                    </td>
                     <td class='screenshotColumn'>
                       <button  class='btn_screen' > <img class='screens' src='${steps[a].screenImage}' alt='undefined'  ></button> 
                    </td>
                    <td class="actionCol">
                        <button id='addStep'></button>
                        <button id='delButton'></button>
                    </td>
                </tr>
                `:element.innerHTML+`
                <tr class="tableRow">
                    <td class='fixedColumns'>
                        <div class='tableData'>${a+1}</div>
                    </td>
                    <td class='stepColumn'>
                        <div title="${safeDisplay(steps[a].step)}" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class='tableData allSteps'>${safeDisplay(steps[a].step)}</div>
                    </td>
                    <td title="${steps[a].dataText}" class='dataColumn ${dataDisplay}'>
                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class='tableData dataCol'>${steps[a].dataText}</div>
                    </td>
                    <td class='expResColumn ${expResultDisplay}'>
                        <div class="tableData expRes" autocomplete="off"  autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" title="enter your expected result here">${steps[a].expRes}</div>
                    </td>
                    <td class='xpathColumn ${xpathDisplay}'>
                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" title="${steps[a].relXpath}" class="tableData xpathData xpathColor">${steps[a].relXpath}</div>
                    </td>
                    <td class='cssColumn ${cssDisplay}'>
                        <div autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" contenteditable="true" class="tableData cssData xpathColor">${steps[a].relCss}</div>
                    </td>
                    <td class="actionCol">
                        <button id='addStep'></button>
                        <button id='delButton'></button>
                    </td>
                </tr>
                `;addEventListenerToImages()}clickCell();0==steps.length&&(document.querySelector(".tablePlaceholder").style.display="")}function toCamelCase(a){return a.replace(/_/g," ").replace(/\s(.)/g,function(b){return b.toUpperCase()}).replace(/\s/g,"").replace(/^(.)/,function(b){return b.toLowerCase()})}
function clickCell(){for(var a=document.getElementById("records-grid").rows,b=0;b<a.length;b++)a[b].cells[7].childNodes[3].addEventListener("click",function(c){c=this.parentNode.parentNode.rowIndex;steps.splice(c-1,1);document.getElementById("records-grid").rows[c-1].remove();addEventListenerToImages()}),a[b].cells[7].childNodes[1].addEventListener("click",function(c){steps.splice(this.parentNode.parentNode.rowIndex,0,{step:"",dataText:"",expRes:"",relXpath:"",relCss:""});displayRows()}),a[b].childNodes[3].addEventListener("input",
function(c){c.data?(steps[this.parentNode.rowIndex-1].step=this.innerText,this.childNodes[1].classList.remove("removeOutline")):this.childNodes[1].classList.add("removeOutline")}),a[b].childNodes[5].addEventListener("input",function(c){c.data?(steps[this.parentNode.rowIndex-1].dataText=this.innerText,this.childNodes[1].classList.remove("removeOutline")):this.childNodes[1].classList.add("removeOutline")}),a[b].childNodes[7].addEventListener("input",function(c){c.data?(steps[this.parentNode.rowIndex-
1].expRes=this.innerText,this.childNodes[1].classList.remove("removeOutline")):this.childNodes[1].classList.add("removeOutline")}),a[b].childNodes[9].addEventListener("input",function(c){c.data?(steps[this.parentNode.rowIndex-1].relXpath=this.innerText,this.childNodes[1].classList.remove("removeOutline")):this.childNodes[1].classList.add("removeOutline")}),a[b].childNodes[11].addEventListener("input",function(c){c.data?(steps[this.parentNode.rowIndex-1].relCss=this.innerText,this.childNodes[1].classList.remove("removeOutline")):
this.childNodes[1].classList.add("removeOutline")})}
toggleElement.addEventListener("click",function(){let a=document.querySelector(".inputFeildContainer"),b=document.querySelector("#updatetitle");this.classList.contains("active")?(this.classList.remove("active"),this.classList.add("inactive"),xpathInput.classList.add("hidden"),xpathInput.classList.remove("show"),toggleToolTip.textContent="Click to set driver command",helperText.innerText="Add custom driver command",a.classList.remove("showElement"),a.classList.add("remove"),b.title="Click to copy all xpaths",
tablePlaceholder.style.height="calc(100% - 244px)"):(this.classList.remove("inactive"),this.classList.add("active"),toggleToolTip.textContent="Click to disable command",xpathInput.classList.add("show"),xpathInput.classList.remove("hidden"),helperText.innerText="",a.classList.add("showElement"),a.classList.remove("remove"),b.title="Click to copy all commands",tablePlaceholder.style.height="calc(100% - 285px)");displayRows()});
recordButton.addEventListener("click",function(a){recording?(recording=!1,recordIcon.style.backgroundImage="url(../../icons/pause_black.svg)",recordIcon.style.animation="none",pauseBtnToolTip.textContent="Click to start recording.",senderId&&browserType.tabs.sendMessage(senderId,{stopRecording:!0})):(recording=!0,recordIcon.style.animation="blinker 1.0s cubic-bezier(.5, 0, 1, 1) infinite alternate",recordIcon.style.backgroundImage="url(../../icons/tcStudio_redDot.svg)",pauseBtnToolTip.textContent=
"Click to stop recording.",senderId&&browserType.tabs.sendMessage(senderId,{openStudio:!0}))});fileName.addEventListener("keyup",async a=>{if(13===(a.which||a.keyCode)&&"what is my sh_id"===a.target.value){var b=await browserType.storage.local.get(["ext_uniq_id"]);if(b.ext_uniq_id){const c=document.createElement("div");c.classList.add("extension__id__wrapper");c.innerHTML=`
                    <div class="extension__id">
                        <div class="extension__id__close"></div>
                        <h4>Your unique sh_id</h4>
                        <div class="extension__id__container">
                            <input type="text" name="extension-id" id="extension-id" value="${b.ext_uniq_id}" readOnly />
                            <div class="extension__id__copy">
                                <div class="icon"></div>
                            </div>
                        </div>
                    </div>
                `;let f=c.querySelector("#extension-id");b=c.querySelector(".extension__id__close");let d=c.querySelector(".extension__id__copy");b.addEventListener("click",()=>c.remove());d.addEventListener("click",async()=>{f.select();document.execCommand("Copy");d.style.backgroundColor="#ffe0a6";setTimeout(()=>d.style.backgroundColor="#ffffff",300)});document.body.appendChild(c);a.target.value=""}}});let videoDb=null;IDBFiles.getFileStorage({name:"tcs_videos"}).then(a=>{videoDb=a;a.clear()});
function saveVideo(a,b){if(videoDb)return videoDb.put(a,b);showSnackbar("Unable to save video.")}function getVideo(a){if(videoDb)return videoDb.get(a);showSnackbar("Unable to get video.")}function deleteVideo(){if(videoDb)return videoDb.clear();showSnackbar("Unable to delete video.")}let videoRecording=!1,streamRecorder,chunks=[],videoType,startVideoRecorderBtn=document.querySelector(".record__screen"),videoContainer=document.querySelector("#video_container"),videoOverlay=document.querySelector("#video_overlay");
var videoModal=document.querySelector("#video_modal"),videoModalCloseButton=document.querySelector("#video_modal_close");let downloadVideoButton=document.querySelector("#download_video_btn"),videoPlayBtn=document.querySelector("#video_play_btn"),videoPauseBtn=document.querySelector("#video_pause_btn"),videoStopBtn=document.querySelector("#video_stop_btn"),videoDisplayBtn=document.querySelector("#video_display_btn"),videoDeleteBtn=document.querySelector("#video_delete_btn"),recordingCircle=document.querySelector(".recording-circle");
function hasGetUserMedia(){return!(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)}function pauseScreenRecorder(){streamRecorder.pause();videoRecording=!1}function resumeScreenRecorder(){streamRecorder.resume();videoRecording=!0}function stopScreenRecorder(){streamRecorder.stop();videoRecording=!1}function getDomain(){let a="";for(let b=0;b<steps.length;b++)if(0===steps[b].dataText.indexOf("http")){a=steps[b].dataText;break}return a}
let videoLimitModal=document.querySelector("#video_limit_modal"),videoLimitUpgradeBtn=document.querySelector("#video_limit_modal .upgrade"),videoLimitCancelBtn=document.querySelector("#video_limit_modal .cancel");function openVideoLimitModal(){videoLimitModal.style.display="grid";browserType.runtime.sendMessage({name:"focuse_tcs_window"})}videoLimitUpgradeBtn.addEventListener("click",()=>{videoLimitModal.style.display="none"});
videoLimitCancelBtn.addEventListener("click",()=>{videoLimitModal.style.display="none"});
async function startScreenRecorder(){videoRecording=!0;hasGetUserMedia||showSnackbar("Update your browser to record your screen");const a=await navigator.mediaDevices.getDisplayMedia({audio:!1,video:!0});streamRecorder=new MediaRecorder(a);videoType=streamRecorder.mimeType;streamRecorder.start(500);streamRecorder.ondataavailable=function(b){chunks.push(b.data);600<=chunks.length&&(streamRecorder.stop(),openVideoLimitModal())};streamRecorder.onstart=function(b){videoDisplayBtn.style.display="block";
videoPlayBtn.style.display="none";videoPauseBtn.style.display="block";videoStopBtn.style.display="block";videoDeleteBtn.style.display="none";downloadVideoButton.style.display="none";videoOverlay.style.display="none"};streamRecorder.onresume=function(b){videoDisplayBtn.style.display="block";videoDisplayBtn.style.pointerEvents="auto";videoPlayBtn.style.display="none";videoPauseBtn.style.display="block";recordingCircle.style.backgroundColor="red";recordingCircle.style.animation="recording 1s ease infinite alternate"};
streamRecorder.onpause=function(b){videoDisplayBtn.style.display="block";videoPlayBtn.style.display="block";videoPauseBtn.style.display="none";recordingCircle.style.backgroundColor="grey";recordingCircle.style.animation="none";b=new Blob(chunks,{type:videoType});saveVideo("video",b)};streamRecorder.onstop=function(b){videoDisplayBtn.style.display="block";videoDisplayBtn.style.pointerEvents="auto";videoPauseBtn.style.display="none";videoPlayBtn.style.display="none";videoStopBtn.style.display="none";
videoDeleteBtn.style.display="block";downloadVideoButton.style.display="block";videoModal.style.display="none";videoOverlay.style.zIndex=1;videoOverlay.style.display="flex";videoContainer.onmouseout=null;videoRecording=!1;b=new Blob(chunks,{type:videoType});saveVideo("video",b);streamRecorder.stream.getTracks().forEach(c=>c.stop())};tablePlaceholder.style.height="calc(100% - 256px)";startVideoRecorderBtn.style.display="none"}
startVideoRecorderBtn.addEventListener("click",async()=>{await startScreenRecorder();const a=document.createElement("video");a.srcObject=streamRecorder.stream;a.className+="video_small";a.autoplay=!0;a.muted=!0;videoContainer.appendChild(a);videoContainer.onmouseover=function(){videoOverlay.style.display="flex";videoOverlay.style.alignItems="center";videoOverlay.style.justifyContent="space-around"};videoContainer.onmouseout=function(){videoOverlay.style.display="none"};videoContainer.style.display=
"flex";startVideoRecorderBtn.style.display="none"});downloadVideoButton.addEventListener("click",async()=>{let a=getDomain().replace(/.+\/\/|www.|\..+/g,""),b=getFormattedTime();getVideo("video").then(c=>{if(c){let f=document.querySelector("#downloadFileName input").value||`${a}-${b}`;c=new File([c],f+".webm",{type:videoType});saveAs(c)}else showSnackbar("No Video to save")})});videoModalCloseButton.addEventListener("click",()=>{videoModal.style.display="none";videoOverlay.style.zIndex=1});
videoPlayBtn.addEventListener("click",()=>{streamRecorder&&recording&&resumeScreenRecorder()});videoPauseBtn.addEventListener("click",()=>{streamRecorder&&videoRecording&&pauseScreenRecorder()});videoStopBtn.addEventListener("click",()=>{stopScreenRecorder()});
videoDisplayBtn.addEventListener("click",()=>{videoOverlay.style.zIndex=0;videoModal.style.display="block";var a=document.querySelector("#full_video");videoRecording?(a.srcObject=streamRecorder.stream,a.setAttribute("autoplay","autoplay"),a.removeAttribute("controls")):getVideo("video").then(b=>{a.removeAttribute("autoplay");a.setAttribute("controls","controls");a.srcObject=null;a.src=URL.createObjectURL(b)})});
videoDeleteBtn.addEventListener("click",()=>{deleteVideo("video");chunks=[];document.querySelector(".video_small").remove();videoContainer.style.display="none";tablePlaceholder.style.height="calc(100% - 244px)";startVideoRecorderBtn.style.display="inline-block"});let upgradeContainer=document.querySelector("#upgrade-popup"),upgradeConfirmBtn=document.querySelector("#upgrade-confirm"),upgradeCancelBtn=document.querySelector("#upgrade-cancel"),uiBlockAdsSettings;
upgradeConfirmBtn.addEventListener("click",()=>{upgradeContainer.classList.add("hideElement")});upgradeCancelBtn.addEventListener("click",()=>{upgradeContainer.classList.add("hideElement")});
let recorderCommands={openWebsite:{sentence:"Open website",label:"Open website"},select:{sentence:'select "{value}" from "{name}"',label:"Select from dropdown"},clickAt:{sentence:'Click on "{name}"',label:"Click on element"},doubleClickAt:{sentence:'Double click on "{name}"',label:"Double click on element"},rightClick:{sentence:'Right click on "{name}"',label:"Right click on element"},type:{sentence:'Enter "{value}" into "{name}"',label:"Enter text"},scrollUp:{sentence:"Scroll up",label:"Scroll up"},
scrollDown:{sentence:"Scroll down",label:"Scroll down"},refresh:{sentence:"Reload",label:"Refresh Page"},pressKey:{sentence:"Press {key}",label:"Press key"},drag:{sentence:'Drag "{name}"',label:"Drag element"},drop:{sentence:'Drop to "{name}"',label:"Drop to element"}},commandsContainer=document.querySelector("#sentences"),errorContainer=document.querySelector(".error__container"),bddFormatBtn=document.querySelector(".bdd-format");
function validateSentence(a,b){if("select"===a||"type"===a)if(!b.includes("{value}")||!b.includes("{name}"))throw Error(`Invalid "${recorderCommands[a].label}" sentence: sentence must include {value} and {name}`);if(("clickAt"===a||"doubleClickAt"===a||"rightClick"===a||"drag"===a||"drop"===a)&&!b.includes("{name}"))throw Error(`Invalid "${recorderCommands[a].label}" sentence: sentence must include {name}`);if("pressKey"===a&&!b.includes("{key}"))throw Error(`Invalid "${recorderCommands[a].label}" sentence: sentence must include {key}`);
errorContainer.classList.add("hideElement")}function updateSentences(){browserType.storage.local.get(["recorderCommands"],a=>{if(a.recorderCommands&&0<commandsContainer.children.length)for(let b in a.recorderCommands){let c=commandsContainer.querySelectorAll(`[data-key="${b}"]`)[0];c&&(c.value=a.recorderCommands[b].sentence)}})}
browserType.storage.local.get(["recorderCommands","bddFormat"],a=>{a.recorderCommands||browserType.storage.local.set({recorderCommands});a.bddFormat?bddFormatBtn.innerText="true"===a.bddFormat?"Change to Default Format":"Change to BDD Format":browserType.storage.local.set({bddFormat:"false"});if(a=a.recorderCommands||recorderCommands)for(let b in a){let c=a[b],f=document.createElement("div");f.setAttribute("class","sentence");f.innerHTML=`
        <div class="sentence_label">${c.label}</div>
        <input
        class="sentence_text"
        type="text"
        name="Sentence Text"
        data-key="${b}"
        value='${c.sentence}'
        />
        <div class="actions">
          <div class="reset reset-icon" title="reset sentence"></div>
        </div>
        `;let d=f.querySelector("input");d.addEventListener("input",()=>{errorContainer.classList.add("hideElement")});d.addEventListener("blur",e=>{browserType.storage.local.get(["recorderCommands"],g=>{if(g.recorderCommands)try{validateSentence(b,e.target.value),g.recorderCommands[b].sentence=e.target.value,browserType.storage.local.set({recorderCommands:g.recorderCommands})}catch(k){errorContainer.classList.remove("hideElement"),errorContainer.innerText=k.message}})});f.querySelector(".reset").addEventListener("click",
()=>{browserType.storage.local.get(["translation"],async({translation:e})=>{if(e)if("en"===e.code)d.value=recorderCommands[b].sentence,browserType.storage.local.get(["recorderCommands"],g=>{g.recorderCommands&&(g.recorderCommands[b].sentence=recorderCommands[b].sentence,browserType.storage.local.set({recorderCommands:g.recorderCommands}))});else try{selectedLanguageButton.innerText="...";let g=await translate({from:"en",to:e.code,body:[{text:recorderCommands[b].sentence}]});selectedLanguageButton.innerText=
e.name;g[0].translations&&(d.value=g[0].translations[0].text,browserType.storage.local.get(["recorderCommands"],k=>{k.recorderCommands&&(k.recorderCommands[b].sentence=g[0].translations[0].text,browserType.storage.local.set({recorderCommands:k.recorderCommands}))}))}catch(g){console.log(g)}else d.value=recorderCommands[b].sentence,browserType.storage.local.get(["recorderCommands"],g=>{g.recorderCommands&&(g.recorderCommands[b].sentence=recorderCommands[b].sentence,browserType.storage.local.set({recorderCommands:g.recorderCommands}))})})});
commandsContainer.appendChild(f)}});
bddFormatBtn.addEventListener("click",()=>{browserType.storage.local.get(["recorderCommands","bddFormat"],a=>{a.bddFormat&&"false"!==a.bddFormat?(bddFormatBtn.innerText="Change to BDD Format",browserType.storage.local.set({bddFormat:"false"}),browserType.storage.local.set({recorderCommands},async()=>{updateSentences()})):(bddFormatBtn.innerText="Change to Default Format",browserType.storage.local.set({bddFormat:"true"}),a=a.recorderCommands,a.openWebsite.sentence="When the user opens website",a.select.sentence=
'then the user selects "{value}" from "{name}"',a.clickAt.sentence='then the user clicks on "{name}"',a.doubleClickAt.sentence='then the user double clicks on "{name}"',a.rightClick.sentence='then the user right clicks on "{name}"',a.type.sentence='then the user enters "{value}" into "{name}" field',a.scrollUp.sentence="then the user scrolls up",a.scrollDown.sentence="then the user scrolls down",a.refresh.sentence="then the user reloads the page",a.pressKey.sentence="then the user presses the {key} key",
a.drag.sentence='then the user drags "{name}"',a.drop.sentence='then the user drops to "{name}"',browserType.storage.local.set({recorderCommands:a},()=>{updateSentences()}))})});
save_btn.addEventListener("click",function(a){trackEvent("download");uiBlockAdsSettings&&1===uiBlockAdsSettings.active?browserType.storage.local.get(["save_count"],e=>{if(void 0===e.save_count||null===e.save_count)return browserType.storage.local.set({save_count:0});e.save_count>=uiBlockAdsSettings.nb_actions-1?browserType.storage.local.get(["ttlt"],g=>{"undefined"==typeof g.ttlt||"undefined"==g.ttlt||null==g.ttlt||""==g.ttlt?(upgradeContainer.classList.remove("hideElement"),upgradeContainer.querySelector(".upgrade__popup__message").innerText=
uiBlockAdsSettings.message,upgradeContainer.querySelector("#upgrade-confirm").href=uiBlockAdsSettings.link,upgradeContainer.querySelector("#upgrade-confirm").innerText=uiBlockAdsSettings.action_label):upgradeContainer.classList.add("hideElement");browserType.storage.local.set({save_count:0})}):browserType.storage.local.set({save_count:e.save_count+1})}):browserType.storage.local.set({save_count:0});a=toggleToolTip.textContent.includes("Click to set driver command")?"XPath":"Command";if(steps&&steps.length){a=
[["#","Step","Data","Exp Result",a,"cssSelector"]];let e=document.querySelectorAll(".fixedColumns"),g=document.querySelectorAll(".allSteps"),k=document.querySelectorAll(".dataCol"),m=document.querySelectorAll(".expRes"),n=document.querySelectorAll(".xpathData"),l=document.querySelectorAll(".cssData");var b=steps.map((h,p)=>({index:e[p].innerText,step:g[p].innerText,dataText:k[p].innerText,expRes:m[p].innerText,relXpath:n[p].innerText,relCss:l[p].innerText}));b=b.map(h=>[h.index,h.step,h.dataText,
h.expRes,h.relXpath,h.relCss]);a=a.concat(b);var c=fileName.value.replace(/\s/g,"");b=k[0].innerText.replace(/.+\/\/|www.|\..+/g,"");var f=getFormattedTime();c=c?c:b+"-"+f;downloadData(a,c);var d=new JSZip;steps.forEach((h,p)=>{if(h.screenImage){isthereAnImage=!0;var q=h.screenImage.replace("data:image/jpeg;base64,","");d.file(p+1+"-"+h.step.replaceAll('"',"")+".jpg",q,{base64:!0})}});isthereAnImage&&screenDataColumnChecked&&d.generateAsync({type:"blob"}).then(function(h){saveAs(h,c+"_screenshots")})}else showSnackbar("No data to save")});
function systemInformation(){let a,b=new Date;a=b.toLocaleDateString(void 0,{day:"2-digit",timeZoneName:"short"}).substring(4);return`OS: ${os.platform||""} ${os.version||""} | Browser: ${sys.name||""} ${sys.version.split(".")[0]||""} | Resolution: ${window.screen.availWidth}x${window.screen.availHeight} | Time: ${b.getDate()} ${"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ")[b.getMonth()]} ${b.getFullYear()} / ${b.getHours()}:${b.getMinutes()}:${b.getSeconds()}  ${a}`}
async function downloadData(a,b){let c="";if(2>a.length)return showSnackbar("No Testcases selected");await browserType.storage.local.get(["systemInfoToggle"]);c=`,${systemInformation()}\n`;c+="\n";let f=document.createElement("a"),d=null;a.forEach(e=>{let g=[];e.forEach(k=>{k=k.replaceAll('"','""');g.push(`"${k}"`)});c+=g.join(",")+"\n"});d=new Blob([c],{type:"application/csv;charset=UTF-8"});f.href=window.URL.createObjectURL(d);f.download=b+".csv";document.body.appendChild(f);f.click();document.body.removeChild(f)}
function exportDataInToExcel(a,b){var c=new Date;let f=`,OS: ${os.platform||""} ${os.version||""} | Browser: ${sys.name||""} ${sys.version.split(".")[0]||""} | Resolution: ${window.screen.availWidth}x${window.screen.availHeight} | Time: ${c.getDate()} ${monthNames[c.getMonth()]} ${c.getFullYear()} / ${c.getHours()}:${c.getMinutes()}:${c.getSeconds()}  ${timezone}\n`;var d=window.navigator.userAgent.includes("Windows");Object.keys(a).forEach(function(e){var g=1;dataColumnCheckbox.checked?g+=1:a[e].splice(g,
1);expResultColumnCheckbox.checked?g+=1:a[e].splice(g,1);xpathColumnCheckbox.checked?g+=1:a[e].splice(g,1);cssSelectorColumnCheckbox.checked||a[e].splice(g,1)});a.forEach(function(e){f+=d?e.join(","):e.join("\t");f+="\n"});c=window.document.createElement("a");c.href=window.URL.createObjectURL(new Blob([f],{type:"data:application/vnd.ms-excel;base64,"}));c.download=d?b+".csv":b+".xls";document.body.appendChild(c);c.click()}function getPageUrl(){return window.location.hostname}
function getFormattedTime(){var a=new Date,b=a.getFullYear(),c=a.getMonth()+1,f=a.getDate(),d=a.getHours(),e=a.getMinutes();a=a.getSeconds();return b+"-"+c+"-"+f+"-"+d+"-"+e+"-"+a}function showSnackbar(a){let b=document.querySelector("#snackbar");b.innerText=a;b.className="show";setTimeout(function(){b.className=b.className.replace("show","")},2E3)}
xpathInput.addEventListener("keyup",function(a){xpathText=a.target.value;if(13==a.keyCode){if(!this.value.toLowerCase().includes("xpathvalue")){this.classList.add("wrongXpath");showSnackbar("xpathValue keyword should be there in the command.");return}displayRows();updateCPAttr()}this.value.toLowerCase().includes("xpathvalue")?this.value.toLowerCase().includes("xpathvalue")&&this.classList.remove("wrongXpath"):this.classList.add("wrongXpath")});
window.onload=function(a){trackEvent("open extension");if((a=getExtensionInfo())&&a.version){const b=document.querySelector("#version .version");b&&(b.innerText=`v${a.version}`)}authenticated=!0;tablePlaceholder.innerText="1. Now start your testing.\r\n2. All actions will be converted in english sentence here.\r\n3. For each step unique selector will be generated.\r\n4. Turn on the driver command & set as per requirement to generate command.\r\n5. Download the test case or copy all steps.\r\n6. You can update the file name before exporting it.";
browserType.tabs.query({}).then(b=>{b.forEach(async c=>{try{await browserType.tabs.sendMessage(c.id,{openStudio:!0})}catch(f){}})})};window.onbeforeunload=function(a){videoDb&&videoDb.clear();browserType.tabs.query({}).then(b=>{b.forEach(async c=>{await browserType.tabs.sendMessage(c.id,{closed:!0})})});window.removeEventListener("beforeunload",window.onbeforeunload,!1)};
function notifyMe(a,b){"granted"===Notification.permission&&((new Notification("TestCase Studio",{icon:"../../icons/tcStudio_black.svg",body:b})).onclick=function(){window.focus()})}clearTestCase.addEventListener("click",function(a){document.querySelector(".tablePlaceholder").style.display="";element.innerHTML=null;steps=[];limitReached=!1});copyAllSteps.addEventListener("click",function(){trackEvent("copy steps");copyAllRowsToClipboard(".allSteps")});
copyAllData.addEventListener("click",function(){trackEvent("copy data");copyAllRowsToClipboard(".dataCol")});copyAllExpRes.addEventListener("click",function(){trackEvent("copy exp result");copyAllRowsToClipboard(".expRes")});copyAllXpath.addEventListener("click",function(){trackEvent("copy Xpath");copyAllRowsToClipboard(".xpathData")});copyAllCss.addEventListener("click",function(){trackEvent("copy CSS selector");copyAllRowsToClipboard(".cssData")});
function copyAllRowsToClipboard(a){let b=document.createElement("textarea");b.id="t";b.style.height=0;document.body.appendChild(b);a=document.querySelectorAll(a);for(var c=0;c<a.length;c++)b.value=b.value+"\n"+a[c].innerText;document.querySelector("#t").select();document.execCommand("copy");document.body.removeChild(b)}
function attributeChoicesOption(){attrArr=`,${idAttr.checked?"withid":"withoutid"},${classAttr.checked?"withclass":"withoutclass"},${nameAttr.checked?"withname":"withoutname"},${placeholder.checked?"withplaceholder":"withoutplaceholder"},${textXpath.checked?"withtext":"withouttext"}`;browserType.tabs.sendMessage(senderId,{attrArray:attrArr})}checkboxes.forEach(a=>{a.addEventListener("click",function(){attributeChoicesOption();updateCPAttr()})});
function setAttr(a){idAttr.checked=a.idChecked;classAttr.checked=a.classChecked;nameAttr.checked=a.nameChecked;placeholder.checked=a.placeholderChecked;textXpath.checked=a.textChecked}function updateCPAttr(){browserType.tabs.sendMessage(senderId,{name:"updateCPAttr",data:{idChecked:idAttr.checked,classChecked:classAttr.checked,nameChecked:nameAttr.checked,placeholderChecked:placeholder.checked,textChecked:textXpath.checked}})}
var attributeFilter=document.querySelector(".attributeFilter"),attrFilterBtn=document.querySelector(".attrFilterBtn");
attrFilterBtn.addEventListener("click",function(a){""===attributeFilter.style.display||"none"===attributeFilter.style.display?(browserType.storage.local.set({studioAttributeFilter:"active"},function(){}),attributeFilter.style.display="flex",attrFilterBtn.classList.remove("inactive"),attrFilterBtn.classList.add("active"),tablePlaceholder.style.height="calc(100% - 285px)"):(browserType.storage.local.set({studioAttributeFilter:"inactive"},function(){}),attributeFilter.style.display="none",attrFilterBtn.classList.remove("active"),
attrFilterBtn.classList.add("inactive"),tablePlaceholder.style.height="calc(100% - 244px)")});browserType.storage.local.get(["studioAttributeFilter"],function(a){"active"==a.studioAttributeFilter&&(attributeFilter.style.display="flex",attrFilterBtn.classList.remove("inactive"),attrFilterBtn.classList.add("active"))});var columns=document.querySelector(".columns"),uiConfigBtn=document.querySelector(".uiConfigBtn");let settingsContainer=document.querySelector(".settings__container");
uiConfigBtn.addEventListener("click",function(a){settingsContainer.style.display=""===settingsContainer.style.display||"none"===settingsContainer.style.display?"block":"none"});var dataColumnCheckbox=document.querySelector(".chooseColumns.data"),dataHeader=document.querySelector("#dataHeader");
dataColumnCheckbox.addEventListener("click",function(){var a=document.querySelectorAll(".dataColumn");dataColumnCheckbox.checked?(dataHeader.style.display="table-cell",showAllElements(a),browserType.storage.local.set({dataColumn:"checked"},function(){})):(dataHeader.style.display="none",hideAllElements(a),browserType.storage.local.set({dataColumn:"unchecked"},function(){}))});
browserType.storage.local.get(["dataColumn"],function(a){a.dataColumn&&"checked"!=a.dataColumn&&(dataHeader.style.display="none",dataColumnCheckbox.checked=!1)});var expResultColumnCheckbox=document.querySelector(".chooseColumns.expResult"),expResultHeader=document.querySelector("#expResHeader");
expResultColumnCheckbox.addEventListener("click",function(){var a=document.querySelectorAll(".expResColumn");expResultColumnCheckbox.checked?(expResultHeader.style.display="table-cell",showAllElements(a),browserType.storage.local.set({expResColumn:"checked"},function(){})):(expResultHeader.style.display="none",hideAllElements(a),browserType.storage.local.set({expResColumn:"unchecked"},function(){}))});
browserType.storage.local.get(["expResColumn"],function(a){a.expResColumn&&"checked"!=a.expResColumn&&(expResultHeader.style.display="none",expResultColumnCheckbox.checked=!1)});var xpathColumnCheckbox=document.querySelector(".chooseColumns.xpath"),xpathHeader=document.querySelector("#xpathHeader");
xpathColumnCheckbox.addEventListener("click",function(){var a=document.querySelectorAll(".xpathColumn");xpathColumnCheckbox.checked?(xpathHeader.style.display="table-cell",showAllElements(a),browserType.storage.local.set({xpathDataColumn:"checked"},function(){})):(xpathHeader.style.display="none",hideAllElements(a),browserType.storage.local.set({xpathDataColumn:"unchecked"},function(){}))});
browserType.storage.local.get(["xpathDataColumn"],function(a){a.xpathDataColumn&&"checked"!=a.xpathDataColumn&&(xpathHeader.style.display="none",xpathColumnCheckbox.checked=!1)});var cssSelectorColumnCheckbox=document.querySelector(".chooseColumns.cssSelector"),cssSelectorHeader=document.querySelector("#cssSelectorHeader");
cssSelectorColumnCheckbox.addEventListener("click",function(){var a=document.querySelectorAll(".cssColumn");cssSelectorColumnCheckbox.checked?(cssSelectorHeader.style.display="table-cell",showAllElements(a),browserType.storage.local.set({cssDataColumn:"checked"},function(){})):(cssSelectorHeader.style.display="none",hideAllElements(a),browserType.storage.local.set({cssDataColumn:"unchecked"},function(){}))});
browserType.storage.local.get(["cssDataColumn"],function(a){a.cssDataColumn&&"checked"!=a.cssDataColumn&&(cssSelectorHeader.style.display="none",cssSelectorColumnCheckbox.checked=!1)});function hideAllElements(a){a.forEach(function(b){b.style.display="none"})}function showAllElements(a){a.forEach(function(b){b.style.display="table-cell"})}window.onclick=function(a){a.target.className.includes("tableData")&&(a.target.style.textOverflow="initial")};
document.getElementById("execute_btn").addEventListener("click",function(){trackEvent("execute test on testrigor");if(steps&&steps.length){var a=document.querySelector(".testRigorLink"),b=steps[1].step;b.includes("icon")&&(b=b.replace(" icon",""));b="Press"==b.slice(0,5)?b.replace("Press","type"):b;for(var c="https://app.testrigor.com/external-test?url="+encodeURIComponent(steps[0].dataText)+"&steps="+b,f=2;f<steps.length;f++)b=steps[f].step,steps[f].dataText.includes("******")&&(b=b.replaceAll("******",
steps[f].passwordValue)),b.includes("icon")&&(b=b.replace(" icon","")),b="Press"==b.slice(0,5)?b.replace("Press","type"):b,c=c+"%0A"+b;a.setAttribute("href",c+"&reference=selectorshub&utm_source=selectorshub&utm_medium=tcs&eid=LYFcml")}else showSnackbar("No steps to execute.")});var country,city;function trackEvent(a){"string"!==typeof a&&fetch(`${API_URL}analytics/ads/track`,{method:"post",headers:{"Content-Type":"application/json"},body:JSON.stringify(a)})}
function setCookies(){const a=Math.floor(Date.now()/1E3)+63072E4;chrome.cookies.set({url:"https://selectorshub.com",name:"TestCase Studio authentication",value:"true",secure:!0,expirationDate:a});document.getElementById("register_form").style.display="none";tablePlaceholder.innerText="1. Now start your testing.\r\n2. All actions will be converted in english sentence here.\r\n3. For each step unique selector will be generated.\r\n4. Turn on the driver command & set as per requirement to generate command.\r\n5. Download the test case or copy all steps.\r\n6. You can update the file name before exporting it."}
var span=document.getElementsByClassName("close")[0];span.onclick=function(){modal.style.display="none"};screenToggler.addEventListener("click",function(){screenshootEnabled=!screenshootEnabled;if(this.classList.contains("active")){this.classList.remove("active");this.classList.add("inactive");try{document.querySelectorAll(".screens").style.display="none"}catch(a){}}else this.classList.add("active"),this.classList.remove("inactive")});
var screenShotsCheckbox=document.querySelector(".chooseColumns.Screenshoot"),screenshotHeader=document.querySelector("#screenshotHeader");
screenShotsCheckbox.addEventListener("click",function(){var a=document.querySelectorAll(".btn_screen");screenShotsCheckbox.checked?(screenshotHeader.style.display="table-cell",showAllElements(a),browserType.storage.local.set({screenDataColumn:"checked"},function(){}),screenDataColumnChecked=!0):(screenshotHeader.style.display="none",hideAllElements(a),browserType.storage.local.set({screenDataColumn:"unchecked"},function(){}),screenDataColumnChecked=!1);displayRows()});
browserType.storage.local.get(["screenDataColumn"],function(a){a.screenDataColumn&&"checked"!=a.screenDataColumn&&(screenshotHeader.style.display="none",screenDataColumnChecked=screenShotsCheckbox.checked=!1)});
document.querySelector("#next").addEventListener("click",function(){document.querySelector("#previous").style.visibility="visible";try{actualImage<=imagesArray.length-1&&(modalImg.src=imagesArray[actualImage+1].firstElementChild.src,document.querySelector(".screen_name").innerHTML=actualImage+2+"- "+stepsArray[actualImage+1].firstElementChild.innerHTML,actualImage++,actualImage==imagesArray.length-1&&(this.style.visibility="hidden"))}catch(a){}});
document.querySelector("#previous").addEventListener("click",function(){document.querySelector("#next").style.visibility="visible";0<actualImage&&(modalImg.src=imagesArray[actualImage-1].firstElementChild.src,document.querySelector(".screen_name").innerHTML=actualImage+"- "+stepsArray[actualImage-1].firstElementChild.innerHTML,actualImage--,0==actualImage&&(this.style.visibility="hidden"))});
function addEventListenerToImages(){imagesArray=Array.from(document.querySelectorAll(".btn_screen")).filter((a,b)=>a.firstElementChild.src.includes("undefined")?!1:!0);stepsArray=Array.from(document.querySelectorAll(".stepColumn")).filter((a,b)=>a.parentElement.querySelector(".screenshotColumn")&&!a.parentElement.querySelector(".screenshotColumn").firstElementChild.firstElementChild.src.includes("undefined")?!0:!1);imagesArray.forEach((a,b)=>{a.addEventListener("click",function(){a.firstElementChild.src.includes("undefined")||
(modal.style.display="block");document.querySelector("#next").style.visibility="visible";document.querySelector("#previous").style.visibility="visible";modalImg.src=a.querySelector("img").src;actualImage=b;document.querySelector(".screen_name").innerHTML=actualImage+1+"- "+stepsArray[actualImage].firstElementChild.innerHTML;0==b&&(document.querySelector("#previous").style.visibility="hidden");b==imagesArray.length-1&&(document.querySelector("#next").style.visibility="hidden")})})}
document.addEventListener("keydown",a=>{"none"!=document.querySelector(".modal").style.display&&("37"==a.keyCode&&document.querySelector("#previous").click(),"39"==a.keyCode&&document.querySelector("#next").click())});let adsText=document.querySelector(".ads__text"),adsContainer=document.querySelector(".ads__container"),adsViewer=document.querySelector(".ads__viewer"),dummyVariable="";
const buildAdText=(a,b,c=0)=>{const f=[];dummyVariable=a;a=dummyVariable.split("");a.splice(c,0,"__img__");dummyVariable=a.join("");c=document.createElement("span");c.innerText=dummyVariable;f.push(c);f.forEach(d=>{let e=d.innerText;e.includes("__img__")&&(e=e.replace("__img__",`<img src="${b}" />`),d.innerText="",d.innerHTML=e)});return f};
let offerAdsContainer=document.querySelector("#offer-countdown-ads"),offerText=document.querySelector(".offer__text"),offerCountdown=document.querySelector(".offer__countdown"),offerAdsViewerPrevBtn=document.querySelector(".offer__navigate__prev__btn"),offerAdsViewerNextBtn=document.querySelector(".offer__navigate__next__btn"),offerInterval=null;
const updateOfferContent=(a,b,c)=>{console.log({offer_countdown_enabled:a,offer_countdown_text:b,offer_countdown_end_at:c});if(a)if(offerText.classList.remove("hideElement"),offerCountdown.classList.remove("hideElement"),offerText.innerText=b,c*=1E3,a=Date.now(),a=c-a,0>a)console.log("cleared"),offerText.innerText="",offerCountdown.innerText="",offerText.classList.add("hideElement"),offerCountdown.classList.add("hideElement");else{a=Math.floor(a/1E3);b=Math.floor(a/60);var f=Math.floor(b/60);offerCountdown.innerText=
`${Math.floor(f/24)}d : ${f%24}hr : ${b%60}m : ${a%60}s`;offerInterval&&clearInterval(offerInterval);offerInterval=setInterval(()=>{var d=Date.now();d=Math.floor((c-d)/1E3);let e=Math.floor(d/60),g=Math.floor(e/60);offerCountdown.innerText=`${Math.floor(g/24)}d : ${g%24}hr : ${e%60}m : ${d%60}s`},1E3)}else offerText.classList.add("hideElement"),offerCountdown.classList.add("hideElement")};let offerAdsWrapper=document.querySelector(".offer__ads__container");
const appendAd=({id:a,ad:b,link:c,image_url:f,background_color:d,extensions:e,text_color:g,border_color:k,display_time:m,type:n,action:l})=>{f=buildAdText(b,f);const h=document.createElement("a");h.href=c;h.id=`ad__${a}`;h.className="ad__template";h.setAttribute("target","_blank");h.setAttribute("data-display-time",m);h.setAttribute("title",b);h.style.backgroundColor=d;h.style.border="1px solid "+k;h.style.flexDirection="row";h.innerHTML+=`
  <div class="status__block" style="${n?`display: block; background-color: ${n.color};`:"display: none;"}">${n?.name}</div>
  <div class="ad__text 44444" style="display: flex; alignItems: center;">
      <div style="color: ${g}"></div>
  </div>
  ${l?`<div class="ad__btn" style="background-color: ${l.background_color}">
            <div class="btn">
              <p style="color: ${l.text_color};">${l.name}</p>
              <div class="btn__icon">
                  <img src="${l.icon_url}" />
              </div>
            </div>
         </div>`:""}
`;let p=h.querySelector(".ad__text > div");h.addEventListener("click",async()=>{trackClicks({ext_slug:EXT_SLUG,add_id:a,type:"footer"})});f.forEach(q=>{p.appendChild(q)});e.includes(OFFER_EXT_SLUG.toString())&&offerAdsWrapper.appendChild(h.cloneNode(!0));e.includes(EXT_SLUG.toString())&&adsContainer.appendChild(h.cloneNode(!0))};
let currentIndex=1,_ads,tIntervals=[],tInterval=null,tStartTime=0,tTimeRest=0,tIsPaused=!1,currentOfferIndex=1,offerIntervals=[],offerAdsInterval=null,offerStartTime=0,offerTimeRest=0,offerIsPaused=!1;
const applyInterval=a=>{const b=adsContainer.querySelectorAll(".ad__template");tIntervals.forEach(c=>clearInterval(c));tIntervals=[];tInterval=setInterval(()=>{if(b[currentIndex]){tStartTime=Date.now();let c=adsContainer.querySelector(".ad__template.translate__left");b[currentIndex].classList.remove("no__transition");c.querySelector(".ad__text > div").style.animation="none";c.classList.add("hide__left");b[currentIndex].classList.add("translate__left");if(b[currentIndex].offsetWidth>=adsContainer.offsetWidth){let d=
document.querySelector("#animation-style"),e=`
                        @keyframes scrollText {
                            from{
                                transform: translateX(${b[currentIndex].querySelector(".ad__text").clientWidth+30}px);
                            }
                            to{
                                transform: translateX(-102%);
                            }
                        }`;d.innerHTML=e;b[currentIndex].querySelector(".ad__text > div").style.animation="scrollText 30s linear infinite"}let f=setTimeout(()=>{c.classList.add("no__transition");c.classList.remove("hide__left");c.classList.remove("translate__left");clearTimeout(f);clearInterval(tInterval);tStartTime=0;const d=b[currentIndex].id.replace("ad__",""),e=_ads.filter(g=>g.id==d)[0];currentIndex===b.length-1?currentIndex=0:currentIndex++;tStartTime=Date.now();applyInterval(1E3*e.display_time)},
300)}},a);tIntervals.push(tInterval)},applyOfferInterval=a=>{const b=offerAdsWrapper.querySelectorAll(".ad__template");offerIntervals.forEach(c=>clearInterval(c));offerIntervals=[];offerAdsInterval=setInterval(()=>{if(b[currentOfferIndex]){offerStartTime=Date.now();let c=offerAdsWrapper.querySelector(".ad__template.translate__left");b[currentOfferIndex].classList.remove("no__transition");c.querySelector(".ad__text > div").style.animation="none";c.classList.add("hide__left");b[currentOfferIndex].classList.add("translate__left");
if(b[currentOfferIndex].offsetWidth>=offerAdsWrapper.offsetWidth){let d=document.querySelector("#animation-style-offer"),e=`
                        @keyframes offerScrollText {
                            from{
                                transform: translateX(${b[currentOfferIndex].querySelector(".ad__text").clientWidth+30}px);
                            }
                            to{
                                transform: translateX(-102%);
                            }
                        }`;d.innerHTML=e;b[currentOfferIndex].querySelector(".ad__text > div").style.animation="offerScrollText 30s linear infinite"}let f=setTimeout(()=>{c.classList.add("no__transition");c.classList.remove("hide__left");c.classList.remove("translate__left");clearTimeout(f);clearInterval(offerAdsInterval);offerStartTime=0;const d=b[currentOfferIndex].id.replace("ad__",""),e=_ads.filter(g=>g.id==d)[0];updateOfferContent(e.offer_countdown_enabled,e.offer_countdown_text,e.offer_countdown_end_at);
currentOfferIndex===b.length-1?currentOfferIndex=0:currentOfferIndex++;offerStartTime=Date.now();applyOfferInterval(1E3*e.display_time)},300)}},a);offerIntervals.push(offerAdsInterval)};let adsViewerPrevBtn=document.querySelector(".navigate__prev__btn"),adsViewerNextBtn=document.querySelector(".navigate__next__btn");adsViewerPrevBtn.addEventListener("click",()=>{let a=adsContainer.querySelectorAll(".ad__template");currentIndex-=2;0>currentIndex&&(currentIndex=a.length+currentIndex);applyInterval(400)});
adsViewerNextBtn.addEventListener("click",()=>{applyInterval(400)});offerAdsViewerPrevBtn.addEventListener("click",()=>{let a=offerAdsWrapper.querySelectorAll(".ad__template");const b=a[currentOfferIndex].id.replace("ad__",""),c=_ads.filter(f=>f.id==b)[0];updateOfferContent(c.offer_countdown_enabled,c.offer_countdown_text,c.offer_countdown_end_at);currentOfferIndex-=2;0>currentOfferIndex&&(currentOfferIndex=a.length+currentOfferIndex);applyOfferInterval(400)});
offerAdsViewerNextBtn.addEventListener("click",()=>{const a=offerAdsWrapper.querySelectorAll(".ad__template")[currentOfferIndex].id.replace("ad__",""),b=_ads.filter(c=>c.id==a)[0];updateOfferContent(b.offer_countdown_enabled,b.offer_countdown_text,b.offer_countdown_end_at);applyOfferInterval(400)});const displayAds=a=>{clearInterval(tInterval);clearInterval(offerAdsInterval);offerStartTime=tStartTime=0;_ads=a;a.forEach((b,c)=>appendAd(b,c))};
let adsSection=document.querySelector(".right__section"),topAdsContainer=document.querySelector(".top_ads__container"),topAdsViewer=document.querySelector(".top_ads__viewer"),top_currentIndex=1,_top_ads,top_tIntervals=[],top_tInterval=null,top_tStartTime=0,top_tTimeRest=0,top_tIsPaused=!1;
const topAppendAd=({id:a,ad:b,link:c,image_url:f,background_color:d,text_color:e,border_color:g,display_time:k,type:m,action:n})=>{f=buildAdText(b,f);const l=document.createElement("a");l.href=c;l.id=`top_ad__${a}`;l.className="top_ad__template";l.setAttribute("target","_blank");l.setAttribute("top_data-display-time",k);l.setAttribute("top_title",b);l.style.backgroundColor=d;l.style.border="1px solid "+g;l.innerHTML+=`
        <div class="top_status__block" style="${m?`display: block; background-color: ${m.color};`:"display: none;"}">${m?.name}</div>
        <div class="top_ad__text" style="display: flex; alignItems: center;">
            <div style="color: ${e}"></div>
        </div>
        <div class="top_ad__btn" style="background-color: ${n.background_color}">
            <div class="top_btn">
            <p style="color: ${n.text_color};">${n.name}</p>
                <div class="top_btn__icon">
                    <img src="${n.icon_url}" />
                </div>
            </div>
            </div>
    `;let h=l.querySelector(".top_ad__text > div");l.addEventListener("click",async()=>{trackClicks({ext_slug:TOP_EXT_SLUG,add_id:a,type:"footer"})});f.forEach(p=>{h.appendChild(p)});topAdsContainer.appendChild(l)},topApplyInterval=a=>{const b=document.querySelectorAll(".top_ad__template");top_tIntervals.forEach(c=>clearInterval(c));top_tIntervals=[];top_tInterval=setInterval(()=>{if(b[top_currentIndex]){top_tStartTime=Date.now();let c=document.querySelector(".top_ad__template.top_translate__left");
b[top_currentIndex].classList.remove("top_no__transition");c.querySelector(".top_ad__text > div").style.animation="none";c.classList.add("top_hide__left");b[top_currentIndex].classList.add("top_translate__left");if(b[top_currentIndex].offsetWidth>=topAdsContainer.offsetWidth){let d=document.querySelector("#animation-style"),e=`
                        @keyframes scrollText {
                            from{
                                transform: translateX(${b[top_currentIndex].querySelector(".top_ad__text").clientWidth+30}px);
                            }
                            to{
                                transform: translateX(-102%);
                            }
                        }`;d.innerHTML=e;b[top_currentIndex].querySelector(".top_ad__text > div").style.animation="scrollText 30s linear infinite"}let f=setTimeout(()=>{c.classList.add("top_no__transition");c.classList.remove("top_hide__left");c.classList.remove("top_translate__left");clearTimeout(f);clearInterval(top_tInterval);top_tStartTime=0;const d=b[currentIndex].id.replace("top_ad__",""),e=top_ads.filter(g=>g.id==d)[0];top_currentIndex===b.length-1?top_currentIndex=0:top_currentIndex++;top_tStartTime=
Date.now();topApplyInterval(1E3*e.display_time)},300)}},a);top_tIntervals.push(top_tInterval)};let topAdsViewerPrevBtn=document.querySelector(".top_navigate__prev__btn"),topAdsViewerNextBtn=document.querySelector(".top_navigate__next__btn");topAdsViewerPrevBtn.addEventListener("click",()=>{let a=document.querySelectorAll(".top_ad__template");top_currentIndex-=2;0>top_currentIndex&&(top_currentIndex=a.length+top_currentIndex);topApplyInterval(400,"prev")});
topAdsViewerNextBtn.addEventListener("click",()=>{topApplyInterval(400,"next")});
const topDisplayAds=a=>{clearInterval(top_tInterval);top_tStartTime=0;top_ads=a;a.forEach((b,c)=>topAppendAd(b,c))},changeFooterStyles=a=>{let b=document.querySelector(".infoBlock"),c=document.querySelector(".requestHeader.pro"),f=document.querySelector(".requestHeader.review-link"),d=document.querySelector(".ads__info__icon"),e=document.querySelector(".changelog"),g=e.previousElementSibling,k=document.querySelectorAll(".ads__navigation__btn"),m=document.querySelector(".ads__viewer"),n=document.querySelector(".popup__actions__container"),
l=document.querySelector(".theme-toggle");"popup"===a?(k.forEach(h=>h.classList.add("ads__navigation__btn__popup")),browserType.storage.local.get(["ttlt"],h=>{"undefined"==typeof h.ttlt||"undefined"==h.ttlt||null==h.ttlt||""==h.ttlt?(m.classList.add("ads__viewer__popup"),c.classList.add("hideElement"),f.classList.add("hideElement"),e.classList.add("hideElement"),d.classList.add("hideElement"),g.classList.add("hideElement"),l.classList.add("hideElement"),n.classList.remove("hideElement"),b.classList.add("infoBlockPopUp")):
(n.classList.add("hideElement"),b.classList.remove("infoBlockPopUp"))})):(k.forEach(h=>h.classList.remove("ads__navigation__btn__popup")),b.classList.remove("infoBlockPopUp"),m.classList.remove("ads__viewer__popup"),c.classList.remove("hideElement"),f.classList.remove("hideElement"),e.classList.remove("hideElement"),d.classList.remove("hideElement"),g.classList.remove("hideElement"),l.classList.remove("hideElement"),n.classList.add("hideElement"))};let keepAdsBtn=document.querySelector(".popup__action.keep__ads");
keepAdsBtn.addEventListener("click",()=>{changeFooterStyles("footer")});let timeout;function createImageContainer({id:a,display_time:b,link:c,image_url:f},d=!1){let e=document.createElement("a");e.href=c;e.setAttribute("target","_blank");e.setAttribute("data-dt",b);e.classList.add("image__link");d&&e.classList.add("displayed");e.innerHTML=`<img src="${f}" alt="${c}" /> `;e.addEventListener("click",async()=>{trackClicks({ext_slug:EXT_SLUG,add_id:a,type:"images"})});return e}
function displayPrevAd(){clearTimeout(timeout);var a=document.querySelector(".image__link.displayed");a.classList.remove("displayed");a.previousElementSibling?(a.previousElementSibling.classList.add("displayed"),a=a.previousElementSibling.getAttribute("data-dt")):(a.parentElement.lastElementChild.classList.add("displayed"),a=a.parentElement.lastElementChild.getAttribute("data-dt"));timeout=setTimeout(displayNextAd,1E3*a)}
function displayNextAd(){clearTimeout(timeout);var a=document.querySelector(".image__link.displayed");a.classList.remove("displayed");a.nextElementSibling?(a.nextElementSibling.classList.add("displayed"),a=a.nextElementSibling.getAttribute("data-dt")):(a.parentElement.firstElementChild.classList.add("displayed"),a=a.parentElement.firstElementChild.getAttribute("data-dt"));timeout=setTimeout(displayNextAd,1E3*a)}let prevBtn=document.querySelector(".prev__ad__img"),nextBtn=document.querySelector(".next__ad__img");
prevBtn.addEventListener("click",displayPrevAd);nextBtn.addEventListener("click",displayNextAd);
const displayAllAds=async a=>{if(a.status){const b=a.footer_ads.filter(c=>c.extensions.includes(TOP_EXT_SLUG)&&c.browsers.map(f=>f.toLowerCase()).includes(platform));0<b.length&&b[0].link&&(topDisplayAds(b),setTimeout(()=>{const c=document.querySelectorAll(".top_ad__template");currentIndex=1;c[0].classList.add("top_translate__left");let f=c[0].querySelector(".top_ad__text"),d=document.querySelector("#animation-style");c[0].offsetWidth>=topAdsContainer.offsetWidth&&(d.innerHTML=`
                        @keyframes scrollText {
                            from{
                                transform: translateX(${f.clientWidth+30}px);
                            }
                            to{
                                transform: translateX(-102%);
                            }
                        }`,c[0].querySelector(".top_ad__text > div").style.animation="scrollText 30s linear infinite");tStartTime=Date.now();topApplyInterval(1E3*b[0].display_time);c.forEach(e=>{e.addEventListener("mouseenter",()=>{top_tIsPaused||(e.children[1].children[0].style.animationPlayState="paused",clearInterval(top_tInterval),top_tTimeRest=Date.now()-top_tStartTime,top_tIsPaused=!0)});e.addEventListener("mouseleave",()=>{if(top_tIsPaused){e.children[1].children[0].style.animationPlayState=
"running";var g=e.getAttribute("data-display-time");if(g=parseInt(g))top_tStartTime=Date.now()-top_tTimeRest,topApplyInterval(1E3*g-top_tTimeRest),top_tIsPaused=!1}})})},200));if(0<a.footer_ads.length){let c=a.footer_ads.filter(d=>d.extensions.includes(OFFER_EXT_SLUG.toString()));1===c.length&&(c[0].offer_countdown_enabled||(offerAdsContainer.style.border="none"),offerAdsContainer.classList.remove("hideElement"),adsViewerPrevBtn.classList.add("hideElement"),adsViewerNextBtn.classList.add("hideElement"));
0<c.length?(adsSection.classList.remove("hideElement"),offerAdsContainer.classList.remove("hideElement"),updateOfferContent(c[0].offer_countdown_enabled,c[0].offer_countdown_text,c[0].offer_countdown_end_at)):offerAdsContainer.classList.add("hideElement");let f=a.footer_ads.filter(d=>(d.extensions.includes(EXT_SLUG.toString())||d.extensions.includes(OFFER_EXT_SLUG.toString()))&&d.browsers.map(e=>e.toLowerCase()).includes(platform));displayAds(f);setTimeout(()=>{if(0<f.length&&f[0].link){var d=adsContainer.querySelectorAll(".ad__template");
currentIndex=1;d[0].classList.add("translate__left");var e=d[0].querySelector(".ad__text"),g=document.querySelector("#animation-style");d[0].offsetWidth>=adsContainer.offsetWidth&&(g.innerHTML=`
                        @keyframes scrollText {
                            from{
                                transform: translateX(${e.clientWidth+30}px);
                            }
                            to{
                                transform: translateX(-102%);
                            }
                        }`,d[0].querySelector(".ad__text > div").style.animation="scrollText 30s linear infinite");tStartTime=Date.now();applyInterval(1E3*a.footer_ads[0].display_time);d.forEach(k=>{k.addEventListener("mouseenter",()=>{tIsPaused||(k.children[1].children[0].style.animationPlayState="paused",clearInterval(tInterval),tTimeRest=Date.now()-tStartTime,tIsPaused=!0)});k.addEventListener("mouseleave",()=>{if(tIsPaused){k.children[1].children[0].style.animationPlayState="running";var m=k.getAttribute("data-display-time");
if(m=parseInt(m))tStartTime=Date.now()-tTimeRest,applyInterval(1E3*m-tTimeRest),tIsPaused=!1}})})}0<c.length&&(d=offerAdsWrapper.querySelectorAll(".ad__template"),currentOfferIndex=1,d[0].classList.add("translate__left"),e=d[0].querySelector(".ad__text"),g=document.querySelector("#animation-style-offer"),d[0].offsetWidth>=offerAdsWrapper.offsetWidth&&(g.innerHTML=`
                        @keyframes offerScrollText {
                            from{
                                transform: translateX(${e.clientWidth+30}px);
                            }
                            to{
                                transform: translateX(-102%);
                            }
                        }`,d[0].querySelector(".ad__text > div").style.animation="offerScrollText 30s linear infinite"),offerStartTime=Date.now(),applyOfferInterval(1E3*c[0].display_time),d.forEach(k=>{k.addEventListener("mouseenter",()=>{offerIsPaused||(k.children[1].children[0].style.animationPlayState="paused",clearInterval(offerAdsInterval),offerTimeRest=Date.now()-offerStartTime,offerIsPaused=!0)});k.addEventListener("mouseleave",()=>{if(offerIsPaused){k.children[1].children[0].style.animationPlayState=
"running";var m=k.getAttribute("data-display-time");if(m=parseInt(m))offerStartTime=Date.now()-offerTimeRest,applyOfferInterval(1E3*m-offerTimeRest),offerIsPaused=!1}})}))},200)}if(0<a.images_ads.length){adsSection.classList.remove("hideElement");let c=document.querySelector("#image-ads");c.classList.remove("hideElement");let f=c.querySelector(".images__container");a.images_ads=a.images_ads.filter(d=>d.extensions.includes(EXT_SLUG.toString())&&d.browsers.map(e=>e.toLowerCase()).includes(platform));
a.images_ads.forEach((d,e)=>{let g=createImageContainer(d,0===e);f.appendChild(g);0===e&&(timeout=setTimeout(displayNextAd,1E3*d.display_time))})}0<a.popup_ads.length&&browserType.storage.local.get(["popup_ads_sessions"],({popup_ads_sessions:c})=>{void 0===c?browserType.storage.local.set({popup_ads_sessions:{count:0,popped:!1}}):browserType.storage.local.set({popup_ads_sessions:{count:c.count+1,popped:c.popped}});let f=a.popup_ads.filter(d=>d.ext_slug==EXT_SLUG)[0];if(f){let {active:d,time_control:e,
sessions:g}=f;1===d&&(1===g&&(c?.popped||setTimeout(()=>{changeFooterStyles("popup");browserType.storage.local.set({popup_ads_sessions:{count:0,popped:!1}})},1E3*e)),c?.count<g-1?c?.popped||setTimeout(()=>{changeFooterStyles("popup");browserType.storage.local.set({popup_ads_sessions:{count:c.count+1,popped:!0}})},1E3*e):browserType.storage.local.set({popup_ads_sessions:{count:0,popped:!1}}))}});0<a.uiblock__ads.length&&(uiBlockAdsSettings=a.uiblock__ads.filter(c=>c.ext_slug==EXT_SLUG)[0])}};fetchingAds();
function fetchingAds(){browserType.storage.local.get(["ttlt"],a=>{"undefined"==typeof a.ttlt||"undefined"==a.ttlt||null==a.ttlt||""==a.ttlt?fetch(`${newAPiUrl}all-ads`,{cache:"no-store"}).then(b=>b.json()).then(async b=>{displayAllAds(b)}):browserType.storage.local.remove("fetched_ads")})}
document.addEventListener("DOMContentLoaded",function(){document.getElementById("version").addEventListener("click",function(){isEdge?chrome.tabs.update({url:"edge://extensions/?id=jdglgpgchkgiciogpolofelfdfkdgfcg"}):chrome.tabs.update({url:"chrome://extensions/?id=loopjjegnlccnhgfehekecpanpmielcj"})})});
function getExtensionInfo(){const a={name:"",version:""};"undefined"!==typeof chrome&&(-1!==navigator.userAgent.indexOf("Firefox")?a.name="Firefox":-1!==navigator.userAgent.indexOf("Edg")?a.name="Edge":a.name="Chrome");a.version="Firefox"===a.name?browser.runtime.getManifest().version:chrome.runtime.getManifest().version;return a}
function trackClicks(a){const b=(new URLSearchParams({ext_slug:a.ext_slug,add_id:a.add_id,type:a.type})).toString();browserType.storage.local.get(["trackedQueries"],c=>{c=c.trackedQueries||[];c.includes(b)||(c.unshift(b),5<c.length&&(c=c.slice(0,5)),browserType.storage.local.set({trackedQueries:c},()=>{fetch(`${newAPiUrl}link/track?${b}`)}))})};
